/**
 * ═══════════════════════════════════════════════════════════════════
 * SUFIPULSE ATLAS — Strategic Domains Seed Data
 * ═══════════════════════════════════════════════════════════════════
 *
 * The 10 strategic domains that define what SufiPulse wants to become.
 * Every entity must belong to at least one domain.
 * ═══════════════════════════════════════════════════════════════════
 */

import type { StrategicDomain } from './atlas-types';

export const STRATEGIC_DOMAINS: StrategicDomain[] = [
  {
    id: 'kashmiri-sufi',
    domainName: 'Kashmiri Sufi Music',
    description: 'Zero structured authority exists for Kashmiri Sufi music. Blue ocean. SufiPulse can own it entirely — Sufiana Mausiqi, Reshi tradition, Kashmiri poets like Lalleshwari and Nund Rishi.',
    currentAuthority: 10,
    targetAuthority: 100,
    priorityLevel: 'critical',
    targetDate: '2026-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufipulse-originals',
    domainName: 'SufiPulse Originals',
    description: 'SufiPulse original releases, productions, and content. This IS SufiPulse — every original release is authority we fully control. Highest conversion potential.',
    currentAuthority: 20,
    targetAuthority: 100,
    priorityLevel: 'critical',
    targetDate: '2026-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-poetry',
    domainName: 'Sufi Poetry',
    description: 'Poetry is the source material for all Sufi music. Own the lyrics layer — Rumi, Bulleh Shah, Amir Khusro, Shah Latif Bhittai, Sultan Bahu, and the full Sufi poetic canon.',
    currentAuthority: 5,
    targetAuthority: 80,
    priorityLevel: 'high',
    targetDate: '2027-06-30',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-song-interpretation',
    domainName: 'Sufi Song Interpretation',
    description: 'No one explains what Sufi songs mean. Massive content gap. Song-by-song spiritual commentary, lyrical analysis, historical context, and theological depth.',
    currentAuthority: 0,
    targetAuthority: 90,
    priorityLevel: 'high',
    targetDate: '2027-06-30',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-heritage',
    domainName: 'Sufi Heritage',
    description: 'Saints, shrines, festivals — cultural preservation SufiPulse can champion. Dargahs, Urs celebrations, spiritual lineages, and living traditions.',
    currentAuthority: 5,
    targetAuthority: 70,
    priorityLevel: 'high',
    targetDate: '2027-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-saints',
    domainName: 'Sufi Saints',
    description: 'Devotional music is linked to saints. Owning saints = owning the devotional layer. Data Ganj Bakhsh, Moinuddin Chishti, Lal Shahbaz Qalandar, and 5,000+ saints worldwide.',
    currentAuthority: 5,
    targetAuthority: 75,
    priorityLevel: 'medium',
    targetDate: '2027-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-concepts',
    domainName: 'Sufi Concepts',
    description: 'Theological depth differentiates SufiPulse from generic music platforms. Ishq, Fana, Baqa, Dhikr, Sama, Wajd — the spiritual vocabulary of Sufi music explained through sound.',
    currentAuthority: 10,
    targetAuthority: 85,
    priorityLevel: 'medium',
    targetDate: '2027-06-30',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-science',
    domainName: 'Sufi Science',
    description: 'Completely unowned topic. SufiPulse can define the category. Acoustics of devotion, neuroscience of Sama, healing through sound, sacred geometry in music.',
    currentAuthority: 0,
    targetAuthority: 100,
    priorityLevel: 'medium',
    targetDate: '2027-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'sufi-literature',
    domainName: 'Sufi Literature',
    description: 'Literary Journal is the vehicle. Books, manuscripts, academic works, and literary criticism of Sufi poetry. Grow after music authority is established.',
    currentAuthority: 5,
    targetAuthority: 60,
    priorityLevel: 'low',
    targetDate: '2028-06-30',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
  {
    id: 'global-discovery',
    domainName: 'Global Sufi Discovery',
    description: 'Broad discovery for generic queries — "sufi music", "qawwali songs", "sufi meditation music". Chase after niches are won. High volume but low advantage.',
    currentAuthority: 5,
    targetAuthority: 50,
    priorityLevel: 'low',
    targetDate: '2028-12-31',
    entityCount: 0,
    publishedCount: 0,
    convertingCount: 0,
    isActive: true,
  },
];
