"use client";

import { useEffect, useRef, useState } from 'react';
import JSZip from 'jszip';
import type { CMSRelease } from '@/lib/cms-storage';

import {
  type SubtitleStatus,
  type ASSStylePack,
  ALL_LANGUAGES,
  DEFAULT_STYLE_NAME,
  DEFAULT_STYLE_PACK,
} from './release-constants';
import {
  cueTimeToSeconds,
  secondsToCueTime,
  triggerBlobDownload,
  extractFilenameFromDisposition,
  parseSubtitleFile,
  parseAssFile,
  parseAssStyles,
} from './subtitle-utils';

// ── Local types (re-exported for page.tsx and sub-routes) ─────────────────────

export type DeliveryState =
  | 'web_only'
  | 'synced_to_youtube'
  | 'manual_upload_pending'
  | 'manual_upload_completed'
  | 'sync_failed';

export type CaptionTrackMeta = {
  captionId?: string;
  language?: string;
  lastSyncHash?: string;
  lastSyncAttemptAt?: string;
  lastUploadedAt?: string;
  lastExportedAt?: string;
  lastFormat?: 'srt' | 'vtt';
  lastStatus?: 'synced' | 'unchanged' | 'failed';
  deliveryState?: DeliveryState;
  manualUploadActor?: string;
  manualUploadAt?: string;
  manualUploadNotes?: string;
  lastError?: string;
};

export type ContentReadinessState =
  | 'draft'
  | 'editorial_ready'
  | 'web_published'
  | 'youtube_delivery_in_progress'
  | 'fully_delivered'
  | 'delivery_attention_required';

// ── Module-level constants ────────────────────────────────────────────────────

const CARRY_FORWARD_STORAGE_KEY = 'cms_release_editor_carry_forward_v1';
export const SAMPLE_PREVIEW_DURATION_SECONDS = 8;

// ── Hook ─────────────────────────────────────────────────────────────────────

export function useReleaseForm({
  releaseId,
  isNew,
  ready,
  onNavigate,
}: {
  releaseId: string;
  isNew: boolean;
  ready: boolean;
  onNavigate: (path: string) => void;
}) {
  // ── Form state ─────────────────────────────────────────────────────────────

  const [form, setForm] = useState<Partial<CMSRelease>>({
    title: '',
    slug: '',
    youtubeId: '',
    youtubeChannelId: '',
    youtubeChannelUrl: '',
    description: '',
    releaseDate: new Date().toISOString().split('T')[0],
    durationSeconds: 0,
    durationFormatted: '0:00',
    viewCount: 0,
    likeCount: 0,
    status: 'draft',
    contentReadinessState: 'draft',
    enableLyrics: true,
    enableCommentary: true,
    enableSponsors: false,
    enableAdoption: true,
    enableCredits: true,
    publicCommentary: [
      { id: 'context', title: 'Historical Context', content: '', isPublished: true },
      { id: 'theme', title: 'Thematic Interpretation', content: '', isPublished: true },
    ],
    publicSponsorsIntro: '',
    publicSponsors: [],
    publicCredits: {
      artistic: { leadVocalist: '', lyricist: '', composer: '', musicProducer: '', backgroundVocals: '' },
      production: { recordedAt: '', recordingEngineer: '', mixMaster: '', soundDesign: '', productionSupervision: '' },
      visual: { videoDirection: '', editing: '', thumbnailDesign: '', artwork: '' },
      literary: { romanTransliteration: '', englishTranslation: '', thematicInterpretation: '', proofreading: '' },
      rights: { publishedBy: '', platform: '', registeredReleaseId: '', releaseDateText: '', copyrightHolder: '', licensingText: '', licensingUrl: '' },
    },
    availableLanguages: ['en', 'ur', 'ar', 'fa', 'hi', 'pa', 'tr', 'sd', 'skr', 'bal', 'ps', 'ks', 'bn', 'gu', 'mr', 'ta', 'en-rom'],
    defaultLanguage: 'en',
    lyrics: {},
    lyricsStructure: {},
    masterTimingVersion: 1,
    subtitleCues: [],
    subtitleTranslations: {},
    subtitleLanguageStatuses: {},
    subtitleLanguageAssignments: {},
    subtitleStylePacks: { [DEFAULT_STYLE_NAME]: { ...DEFAULT_STYLE_PACK } },
    subtitleReviewLogs: [],
    youtubeSubtitleAutoSync: true,
    youtubeCaptionTracks: {},
  });

  const [originalForm, setOriginalForm] = useState<Partial<CMSRelease> | null>(null);
  const [loading, setLoading] = useState(!isNew);
  const [notFound, setNotFound] = useState(false);
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<'info' | 'content' | 'subtitles'>('info');
  const [exportingZip, setExportingZip] = useState(false);
  const [youtubeSyncing, setYoutubeSyncing] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [carryForwardNotice, setCarryForwardNotice] = useState<string | null>(null);

  // Subtitle / language UI state
  const [selectedSubtitleLanguage, setSelectedSubtitleLanguage] = useState('en');
  const [selectedLyricsStructureLanguage, setSelectedLyricsStructureLanguage] = useState('en');
  const [referenceLanguage, setReferenceLanguage] = useState('en');
  const [sideBySideMode, setSideBySideMode] = useState(true);
  const [selectedStyleName, setSelectedStyleName] = useState(DEFAULT_STYLE_NAME);
  const [autoTranslatingLang, setAutoTranslatingLang] = useState<string | null>(null);

  // Preview state
  const [previewCueId, setPreviewCueId] = useState<string | null>(null);
  const [previewPanelPosition, setPreviewPanelPosition] = useState({ x: 50, y: 84 });
  const [previewInfoPosition, setPreviewInfoPosition] = useState({ x: 8, y: 9 });
  const [previewInfoWidth, setPreviewInfoWidth] = useState(420);
  const [previewCanvasWidth, setPreviewCanvasWidth] = useState(0);
  const [previewTime, setPreviewTime] = useState(0);
  const [previewPlaying, setPreviewPlaying] = useState(false);
  const [lockAllCuePositions, setLockAllCuePositions] = useState(false);
  const [previewYouTubeReady, setPreviewYouTubeReady] = useState(false);
  const [previewVideoDuration, setPreviewVideoDuration] = useState<number | null>(null);
  const [previewOrigin, setPreviewOrigin] = useState('');
  const [showSafeGuides, setShowSafeGuides] = useState(true);
  const [autoAdvanceAfterStamp, setAutoAdvanceAfterStamp] = useState(true);

  // Review / delivery state
  const [reviewActor, setReviewActor] = useState('Editorial Admin');
  const [reviewComment, setReviewComment] = useState('');
  const [manualUploadActor, setManualUploadActor] = useState('Editorial Admin');
  const [manualUploadNotes, setManualUploadNotes] = useState<Record<string, string>>({});

  // Bulk cue operations
  const [selectedCueIds, setSelectedCueIds] = useState<Set<string>>(new Set());
  const [shiftTimingOffset, setShiftTimingOffset] = useState(0);
  const [bulkKaraokeEffect, setBulkKaraokeEffect] = useState<'none' | 'k' | 'kf' | 'ko'>('kf');
  const [bulkKaraokeDurationsMs, setBulkKaraokeDurationsMs] = useState('');

  // Lyrics placeholder panel
  const [lyricsPlaceholderOpen, setLyricsPlaceholderOpen] = useState(false);
  const [lyricsPlaceholderDraft, setLyricsPlaceholderDraft] = useState('');
  const [lyricsPlaceholderNote, setLyricsPlaceholderNote] = useState<string | null>(null);
  const [lyricsPlaceholderScope, setLyricsPlaceholderScope] = useState<'all' | 'published' | 'single'>('all');
  const [lyricsPlaceholderBlockId, setLyricsPlaceholderBlockId] = useState('');
  const [lyricsPlaceholderSyncLineRef, setLyricsPlaceholderSyncLineRef] = useState(true);

  // YouTube integration
  const [youtubeIntegrationStatus, setYoutubeIntegrationStatus] = useState<{
    configured: boolean;
    missing: string[];
    message?: string;
  } | null>(null);
  const [fetchedYouTubeChannel, setFetchedYouTubeChannel] = useState<{
    channelId: string;
    channelTitle?: string;
    channelUrl: string;
    title?: string;
    durationSeconds?: number;
    durationFormatted?: string;
    thumbnailUrl?: string;
  } | null>(null);
  const [youtubeChannelLookupLoading, setYoutubeChannelLookupLoading] = useState(false);

  // Workflow
  const [expandedWorkflowStepId, setExpandedWorkflowStepId] = useState<string | null>(null);

  // Undo / redo
  const [history, setHistory] = useState<Partial<CMSRelease>[]>([]);
  const [historyIndex, setHistoryIndex] = useState(0);

  // ── Refs ───────────────────────────────────────────────────────────────────

  const previewCanvasRef = useRef<HTMLDivElement>(null);
  const previewYouTubeIframeRef = useRef<HTMLIFrameElement>(null);
  const timelineRef = useRef<HTMLDivElement>(null);
  const liveRef = useRef({ form, lockAllCuePositions: false });
  const carryForwardInitRef = useRef(false);

  // Keep liveRef current every render
  liveRef.current = { form, lockAllCuePositions };

  // Derived
  const hasUnsavedChanges = originalForm != null && JSON.stringify(form) !== JSON.stringify(originalForm);

  // ── Effects ────────────────────────────────────────────────────────────────

  // Load release when ready (auth confirmed by caller)
  useEffect(() => {
    if (ready && !isNew && releaseId) void loadRelease();
  }, [ready, releaseId, isNew]);

  // Carry-forward defaults for new releases
  useEffect(() => {
    if (!isNew || carryForwardInitRef.current) return;
    carryForwardInitRef.current = true;
    const { formData, applied } = applyCarryForwardDefaults(form);
    if (applied > 0) {
      setForm(formData);
      setCarryForwardNotice(`Auto-applied ${applied} reusable default field${applied === 1 ? '' : 's'} from your last saved release.`);
    }
  }, [isNew]);

  // YouTube channel lookup on youtubeId change
  useEffect(() => {
    const youtubeId = String(form.youtubeId || '').trim();
    if (!/^[A-Za-z0-9_-]{11}$/.test(youtubeId)) {
      setFetchedYouTubeChannel(null);
      setYoutubeChannelLookupLoading(false);
      return;
    }

    let cancelled = false;
    const timer = setTimeout(async () => {
      try {
        setYoutubeChannelLookupLoading(true);
        const res = await fetch(`/api/youtube/video-metadata?youtubeId=${encodeURIComponent(youtubeId)}`);
        const data = await res.json();
        if (cancelled) return;
        if (!res.ok || !data?.channelId) { setFetchedYouTubeChannel(null); return; }
        setFetchedYouTubeChannel({
          channelId: String(data.channelId || ''),
          channelTitle: String(data.channelTitle || ''),
          channelUrl: String(data.channelUrl || ''),
        });
      } catch {
        if (!cancelled) setFetchedYouTubeChannel(null);
      } finally {
        if (!cancelled) setYoutubeChannelLookupLoading(false);
      }
    }, 350);

    return () => { cancelled = true; clearTimeout(timer); };
  }, [form.youtubeId]);

  // Auto-fill channel fields from fetched metadata
  useEffect(() => {
    if (!fetchedYouTubeChannel) return;
    setForm((prev) => {
      const next = { ...prev };
      let changed = false;

      // Senior Logic: If it's a new release and title is empty, use the fetched YouTube title
      if (isNew && !String(prev.title || '').trim() && fetchedYouTubeChannel.title) {
        next.title = fetchedYouTubeChannel.title;
        // Also auto-generate slug if not manually touched
        if (slugAutoGenerated) {
          next.slug = fetchedYouTubeChannel.title.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
        }
        changed = true;
      }

      // Senior Logic: Auto-fill duration for validation bypass
      if (isNew && (!prev.durationSeconds || prev.durationSeconds === 0) && fetchedYouTubeChannel.durationSeconds) {
        next.durationSeconds = fetchedYouTubeChannel.durationSeconds;
        next.durationFormatted = fetchedYouTubeChannel.durationFormatted || '0:00';
        changed = true;
      }

      if (!String(prev.youtubeChannelId || '').trim() && fetchedYouTubeChannel.channelId) {
        next.youtubeChannelId = fetchedYouTubeChannel.channelId;
        changed = true;
      }
      if (!String(prev.youtubeChannelUrl || '').trim() && fetchedYouTubeChannel.channelUrl) {
        next.youtubeChannelUrl = fetchedYouTubeChannel.channelUrl;
        changed = true;
      }
      return changed ? next : prev;
    });
  }, [fetchedYouTubeChannel, isNew, slugAutoGenerated]);

  // YouTube integration status check
  useEffect(() => {
    if (isNew) return;
    const checkIntegration = async () => {
      try {
        const response = await fetch('/api/integrations/youtube-status');
        const data = await response.json();
        if (response.ok) {
          setYoutubeIntegrationStatus({
            configured: Boolean(data?.configured),
            missing: Array.isArray(data?.missing) ? data.missing : [],
            message: data?.message,
          });
        }
      } catch { /* keep null */ }
    };
    void checkIntegration();
  }, [isNew]);

  // Preview canvas width observer
  useEffect(() => {
    const canvas = previewCanvasRef.current;
    if (!canvas) return;
    const syncWidth = () => setPreviewCanvasWidth(canvas.getBoundingClientRect().width || 0);
    syncWidth();
    const observer = new ResizeObserver(() => syncWidth());
    observer.observe(canvas);
    window.addEventListener('resize', syncWidth);
    return () => { observer.disconnect(); window.removeEventListener('resize', syncWidth); };
  }, []);

  // Preview origin for YouTube iframe
  useEffect(() => {
    if (typeof window !== 'undefined') setPreviewOrigin(window.location.origin);
  }, []);

  // YouTube player message listener
  useEffect(() => {
    const handlePlayerMessage = (event: MessageEvent) => {
      if (event.source !== previewYouTubeIframeRef.current?.contentWindow) return;
      let payload: any = event.data;
      if (typeof payload === 'string') { try { payload = JSON.parse(payload); } catch { return; } }
      if (!payload || typeof payload !== 'object') return;

      if (payload.event === 'onReady') {
        setPreviewYouTubeReady(true);
        if (previewTime > 0) sendPreviewYouTubeCommand('seekTo', [previewTime, true]);
        return;
      }
      if (payload.event === 'onStateChange') {
        const state = Number(payload.info);
        if (state === 1) setPreviewPlaying(true);
        if (state === 0 || state === 2) setPreviewPlaying(false);
        return;
      }
      if (payload.event === 'infoDelivery' && payload.info) {
        if (typeof payload.info.currentTime === 'number') setPreviewTime(payload.info.currentTime);
        if (typeof payload.info.duration === 'number' && Number.isFinite(payload.info.duration) && payload.info.duration > 0) {
          setPreviewVideoDuration(payload.info.duration);
        }
      }
    };
    window.addEventListener('message', handlePlayerMessage);
    return () => window.removeEventListener('message', handlePlayerMessage);
  }, []);

  // Preview playback timer
  useEffect(() => {
    if (!previewPlaying) return;
    const cueMaxEnd = Math.max(0, ...(form.subtitleCues || []).map((cue) => cueTimeToSeconds(cue.endTime)));
    const maxKnownDuration = Math.max(cueMaxEnd, Number(previewVideoDuration || 0), Number(form.durationSeconds || 0));
    const maxEnd = maxKnownDuration > 0 ? maxKnownDuration : SAMPLE_PREVIEW_DURATION_SECONDS;
    const timer = window.setInterval(() => {
      setPreviewTime((current) => {
        const next = current + 0.25;
        if (next >= maxEnd) { setPreviewPlaying(false); return maxEnd; }
        return next;
      });
    }, 250);
    return () => window.clearInterval(timer);
  }, [previewPlaying, form.subtitleCues, form.durationSeconds, previewVideoDuration]);

  // Auto-advance active cue with preview time
  useEffect(() => {
    if (!(form.subtitleCues || []).length) return;
    const activeCue = (form.subtitleCues || []).find((cue) => {
      const start = cueTimeToSeconds(cue.startTime);
      const end = cueTimeToSeconds(cue.endTime);
      return previewTime >= start && previewTime < end;
    });
    if (activeCue && activeCue.id !== previewCueId) setPreviewCueId(activeCue.id);
  }, [previewTime, form.subtitleCues, previewCueId]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 's') {
        e.preventDefault();
        if (hasUnsavedChanges) {
          const formEl = document.querySelector('form');
          formEl?.dispatchEvent(new Event('submit', { bubbles: true }));
        }
      }
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
      if ((e.ctrlKey || e.metaKey) && e.key === 'y') { e.preventDefault(); redo(); }
      if ((e.ctrlKey || e.metaKey) && e.key === 'e') { e.preventDefault(); if (!isNew) exportAllSubtitlesZip(); }
      if ((e.ctrlKey || e.metaKey) && e.key === 'n') { e.preventDefault(); onNavigate('/admin/cms-releases/new'); }

      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable) return;

      if (e.key === '[') { e.preventDefault(); (document.querySelector('button[title*="Set cue START"]') as HTMLButtonElement | null)?.click(); }
      if (e.key === ']') { e.preventDefault(); (document.querySelector('button[title*="Set cue END"]') as HTMLButtonElement | null)?.click(); }
      if (e.key === ' ') {
        e.preventDefault();
        setPreviewPlaying((prev) => {
          const next = !prev;
          if (/^[A-Za-z0-9_-]{11}$/.test(String(form.youtubeId || ''))) sendPreviewYouTubeCommand(next ? 'playVideo' : 'pauseVideo');
          return next;
        });
      }
      if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
        e.preventDefault();
        const direction = e.key === 'ArrowLeft' ? -1 : 1;
        const amount = e.ctrlKey ? 0.05 : e.shiftKey ? 5 : 1;
        const newTime = Math.max(0, previewTime + direction * amount);
        setPreviewTime(newTime);
        if (/^[A-Za-z0-9_-]{11}$/.test(String(form.youtubeId || ''))) sendPreviewYouTubeCommand('seekTo', [newTime, true]);
      }
      if (e.altKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown' || e.key === 'ArrowLeft' || e.key === 'ArrowRight')) {
        e.preventDefault();
        const cues = form.subtitleCues || [];
        const currentIndex = cues.findIndex((c) => c.id === previewCueId);
        if (currentIndex === -1) return;
        if (e.key === 'ArrowDown' || e.key === 'ArrowRight') { if (currentIndex < cues.length - 1) setPreviewCueId(cues[currentIndex + 1].id); }
        else { if (currentIndex > 0) setPreviewCueId(cues[currentIndex - 1].id); }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [hasUnsavedChanges, isNew, previewTime, previewCueId, form.subtitleCues, form.youtubeId, history, historyIndex]);

  // Unsaved changes warning
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (hasUnsavedChanges) { e.preventDefault(); e.returnValue = ''; }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [hasUnsavedChanges]);

  // ── Session Auto-save / Recovery ──────────────────────────────────────────
  const AUTOSAVE_PREFIX = 'sufipulse_autosave_';
  const autosaveKey = `${AUTOSAVE_PREFIX}${releaseId}`;

  useEffect(() => {
    if (loading || !form.id || isNew) return;
    
    const timer = setInterval(() => {
      if (hasUnsavedChanges) {
        try {
          const payload = {
            form,
            timestamp: new Date().toISOString()
          };
          localStorage.setItem(autosaveKey, JSON.stringify(payload));
        } catch (e) { /* ignore */ }
      }
    }, 15000); // Auto-save every 15 seconds

    return () => clearInterval(timer);
  }, [form, hasUnsavedChanges, loading, isNew, autosaveKey]);

  const recoverAutosave = () => {
    try {
      const saved = localStorage.getItem(autosaveKey);
      if (!saved) return;
      const { form: savedForm } = JSON.parse(saved);
      setForm(savedForm);
      setSuccessMessage('Restored your last unsaved changes from this session.');
      localStorage.removeItem(autosaveKey);
    } catch (e) { /* ignore */ }
  };

  const clearAutosave = () => {
    try {
      localStorage.removeItem(autosaveKey);
    } catch (e) { /* ignore */ }
  };

  // ── Load ────────────────────────────────────────────────────────────────────

  const loadRelease = async () => {
    try {
      const res = await fetch(`/api/releases/${releaseId}`);
      if (res.status === 404) { setNotFound(true); return; }
      if (res.ok) {
        const data = await res.json();
        const formData = {
          ...data,
          subtitleCues: data.subtitleCues || [],
          subtitleTranslations: data.subtitleTranslations || {},
          subtitleLanguageStatuses: data.subtitleLanguageStatuses || {},
          subtitleLanguageAssignments: data.subtitleLanguageAssignments || {},
          subtitleStylePacks: Object.keys(data.subtitleStylePacks || {}).length
            ? data.subtitleStylePacks
            : { [DEFAULT_STYLE_NAME]: { ...DEFAULT_STYLE_PACK } },
          subtitleReviewLogs: data.subtitleReviewLogs || [],
          youtubeSubtitleAutoSync: data.youtubeSubtitleAutoSync !== false,
          youtubeCaptionTracks: data.youtubeCaptionTracks || {},
          contentReadinessState: data.contentReadinessState || 'draft',
          masterTimingVersion: data.masterTimingVersion || 1,
          publicCommentary: Array.isArray(data.publicCommentary)
            ? data.publicCommentary
            : [
                { id: 'context', title: 'Historical Context', content: '', isPublished: true },
                { id: 'theme', title: 'Thematic Interpretation', content: '', isPublished: true },
              ],
          publicSponsorsIntro: data.publicSponsorsIntro || '',
          publicSponsors: Array.isArray(data.publicSponsors) ? data.publicSponsors : [],
          publicCredits: data.publicCredits || { artistic: {}, production: {}, visual: {}, literary: {}, rights: {} },
          lyricsStructure: data.lyricsStructure || {},
        };

        const existingBackgroundVocals = String((formData.publicCredits as any)?.artistic?.backgroundVocals || '').trim();
        if (!existingBackgroundVocals && Array.isArray(data.chorusVocalists) && data.chorusVocalists.length > 0) {
          formData.publicCredits = {
            ...(formData.publicCredits || {}),
            artistic: {
              ...((formData.publicCredits as any)?.artistic || {}),
              backgroundVocals: data.chorusVocalists.join(', '),
            },
          } as any;
        }

        setForm(formData);
        setOriginalForm(formData);

        const trackNotes: Record<string, string> = {};
        Object.entries((formData.youtubeCaptionTracks || {}) as Record<string, any>).forEach(([language, meta]) => {
          trackNotes[language] = String((meta as any)?.manualUploadNotes || '');
        });
        setManualUploadNotes(trackNotes);
        setSelectedSubtitleLanguage(data.defaultLanguage || 'en');
        setSelectedLyricsStructureLanguage(data.defaultLanguage || 'en');
        setReferenceLanguage(data.defaultLanguage || 'en');
        setSelectedStyleName(Object.keys(data.subtitleStylePacks || {})[0] || DEFAULT_STYLE_NAME);
        setPreviewCueId(data.subtitleCues?.[0]?.id || null);
        setCarryForwardNotice(null);
      }
    } catch (error) {
      console.error('Failed to load release:', error);
      setErrorMessage('Failed to load release. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Carry-forward ──────────────────────────────────────────────────────────

  const applyCarryForwardDefaults = (baseForm: Partial<CMSRelease>) => {
    try {
      const carryForwardRaw = typeof window !== 'undefined' ? localStorage.getItem(CARRY_FORWARD_STORAGE_KEY) : null;
      const carryForward = carryForwardRaw ? JSON.parse(carryForwardRaw) : null;
      if (!carryForward || typeof carryForward !== 'object') return { formData: baseForm, applied: 0 };

      const formData: Partial<CMSRelease> = { ...baseForm };
      let applied = 0;

      if (!String(formData.youtubeChannelId || '').trim() && String(carryForward.youtubeChannelId || '').trim()) {
        formData.youtubeChannelId = String(carryForward.youtubeChannelId);
        applied += 1;
      }
      if (!String(formData.youtubeChannelUrl || '').trim() && String(carryForward.youtubeChannelUrl || '').trim()) {
        formData.youtubeChannelUrl = String(carryForward.youtubeChannelUrl);
        applied += 1;
      }

      const currentCredits = (formData.publicCredits || {}) as Record<string, any>;
      const defaultCredits = (carryForward.publicCredits || {}) as Record<string, any>;
      const mergedCredits: Record<string, any> = { ...currentCredits };
      ['artistic', 'production', 'visual', 'literary', 'rights'].forEach((section) => {
        const sectionCurrent = { ...(currentCredits[section] || {}) };
        const sectionDefaults = { ...(defaultCredits[section] || {}) };
        Object.keys(sectionDefaults).forEach((field) => {
          if (!String(sectionCurrent[field] || '').trim() && String(sectionDefaults[field] || '').trim()) {
            sectionCurrent[field] = sectionDefaults[field];
            applied += 1;
          }
        });
        mergedCredits[section] = sectionCurrent;
      });
      formData.publicCredits = mergedCredits as any;
      return { formData, applied };
    } catch {
      return { formData: baseForm, applied: 0 };
    }
  };

  const applyCarryForwardToCurrentForm = () => {
    const { formData, applied } = applyCarryForwardDefaults(form);
    if (applied === 0) {
      setSuccessMessage('No reusable defaults were applied. Save a previous release first or clear fields you want auto-filled.');
      return;
    }
    setForm(formData);
    setCarryForwardNotice(`Applied ${applied} reusable default field${applied === 1 ? '' : 's'} from your last saved release.`);
    setSuccessMessage(`Applied ${applied} reusable default field${applied === 1 ? '' : 's'} from previous release defaults.`);
  };

  // ── Form input handlers ────────────────────────────────────────────────────

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    let finalValue: any = type === 'number' ? parseInt(value) : value;

    // Auto-extract YouTube ID if a full URL is pasted into the ID field
    if (name === 'youtubeId') {
      finalValue = extractYouTubeId(finalValue);
    }

    const updated: Partial<CMSRelease> = { ...form, [name]: finalValue };
    
    // Senior Logic: Auto-fetch metadata if ID was changed
    if (name === 'youtubeId' && isNew && finalValue.length === 11) {
       // We don't call the API directly here to avoid race conditions with the debounce timer in the useEffect,
       // but we ensure the form state is ready for the effect to pick it up.
       // The existing useEffect already handles fetching metadata when youtubeId changes.
    }
    if (name === 'status') {
      if (value === 'draft') updated.contentReadinessState = 'draft';
      if (value === 'approved' || value === 'in_review') updated.contentReadinessState = 'editorial_ready';
      if (value === 'published' && !updated.contentReadinessState) updated.contentReadinessState = 'web_published';
    }
    if (name === 'title' && slugAutoGenerated) {
      updated.slug = finalValue.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    }
    if (name === 'slug') setSlugAutoGenerated(false);
    if (fieldErrors[name]) setFieldErrors((prev) => { const n = { ...prev }; delete n[name]; return n; });
    setForm(updated);
  };

  const handleCheckboxChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = e.target;
    setForm({ ...form, [name]: checked });
  };

  const generateSlug = () => {
    const slug = (form.title || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    setForm({ ...form, slug });
    setSlugAutoGenerated(false);
  };

  const extractYouTubeId = (input: string): string => {
    const trimmed = input.trim();
    const patterns = [
      /[?&]v=([A-Za-z0-9_-]{11})/,
      /youtu\.be\/([A-Za-z0-9_-]{11})/,
      /embed\/([A-Za-z0-9_-]{11})/,
      /shorts\/([A-Za-z0-9_-]{11})/,
    ];
    for (const re of patterns) { const m = trimmed.match(re); if (m) return m[1]; }
    if (/^[A-Za-z0-9_-]{11}$/.test(trimmed)) return trimmed;
    return trimmed;
  };

  const handleYouTubePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    const pasted = e.clipboardData.getData('text');
    const extracted = extractYouTubeId(pasted);
    if (extracted !== pasted.trim()) {
      e.preventDefault();
      setForm((prev) => ({ ...prev, youtubeId: extracted }));
      setFieldErrors((prev) => { const n = { ...prev }; delete n.youtubeId; return n; });
    }
  };

  const applyFetchedChannelDefaults = () => {
    if (!fetchedYouTubeChannel) {
      setErrorMessage('No fetched YouTube channel metadata available for this video yet.');
      return;
    }
    setForm({ ...form, youtubeChannelId: fetchedYouTubeChannel.channelId || form.youtubeChannelId || '', youtubeChannelUrl: fetchedYouTubeChannel.channelUrl || form.youtubeChannelUrl || '' });
    setSuccessMessage(`Applied fetched channel defaults${fetchedYouTubeChannel.channelTitle ? ` (${fetchedYouTubeChannel.channelTitle})` : ''}.`);
  };

  // ── Submit ─────────────────────────────────────────────────────────────────

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (saving) return;
    setErrorMessage(null);
    setSuccessMessage(null);

    const newFieldErrors: Record<string, string> = {};
    if (!form.title?.trim()) newFieldErrors.title = 'Title is required';
    if (!form.slug?.trim()) newFieldErrors.slug = 'Slug is required';
    if (!form.youtubeId?.trim()) newFieldErrors.youtubeId = 'YouTube ID is required';
    
    // Senior Logic: If duration is missing, it's usually because metadata hasn't fetched yet
    if (!form.durationSeconds || form.durationSeconds <= 0) {
      if (youtubeChannelLookupLoading) {
        setErrorMessage('Still fetching YouTube metadata... please wait a moment.');
        return;
      }
      newFieldErrors.durationSeconds = 'Duration is required (click "Fetch Metadata" if not auto-filled)';
    }

    if (Object.keys(newFieldErrors).length > 0) {
      setFieldErrors(newFieldErrors);
      setErrorMessage('Please fix the highlighted fields before saving.');
      return;
    }
    setFieldErrors({});

    try {
      setSaving(true);
      const method = isNew ? 'POST' : 'PUT';
      const url = isNew ? '/api/releases' : `/api/releases/${releaseId}`;

      const normalizedChorus = String((form.publicCredits as any)?.artistic?.backgroundVocals || '')
        .split(',').map((name) => name.trim()).filter(Boolean);

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...form, chorusVocalists: normalizedChorus }),
      });

      if (res.ok) {
        const data = await res.json();
        try {
          const carryForwardPayload = {
            youtubeChannelId: data.youtubeChannelId || '',
            youtubeChannelUrl: data.youtubeChannelUrl || '',
            publicCredits: data.publicCredits || {},
            updatedAt: new Date().toISOString(),
          };
          if (typeof window !== 'undefined') localStorage.setItem(CARRY_FORWARD_STORAGE_KEY, JSON.stringify(carryForwardPayload));
        } catch { /* ignore */ }

        setOriginalForm(data);
        setForm(data); // Ensure current form matches exactly what server returned
        setSuccessMessage(`Release "${data.title}" saved successfully${data.youtubeSubtitleAutoSync ? ' and synced to YouTube' : ''}`);

        if (data.youtubeSubtitleAutoSync !== false) {
          await syncYouTubeSubtitles({ releaseId: data.id, mode: 'update-changed', silent: true });
        }

        if (isNew && data.id) {
          // If it's a new release, redirect to the edit page for that ID after a brief delay
          setTimeout(() => {
            onNavigate(`/admin/cms-releases/${data.id}`);
          }, 1500);
        }
      } else {
        const error = await res.json();
        setErrorMessage(`Save failed: ${error.error || 'Unknown error'}`);
      }
    } catch (error) {
      console.error('Failed to save:', error);
      setErrorMessage(`Failed to save release: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setSaving(false);
    }
  };

  // ── Plain save (no form validation — used by sub-routes) ─────────────────

  const handleSave = async () => {
    if (isNew) return handleSubmit({ preventDefault: () => {} } as React.FormEvent);
    setErrorMessage(null);
    setSuccessMessage(null);
    try {
      setSaving(true);
      const res = await fetch(`/api/releases/${releaseId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      if (res.ok) {
        const data = await res.json();
        setOriginalForm(data);
        setForm(data);
        setSuccessMessage('Saved.');
        if (data.youtubeSubtitleAutoSync !== false) {
          await syncYouTubeSubtitles({ releaseId: data.id, mode: 'update-changed', silent: true });
        }
      } else {
        const error = await res.json();
        setErrorMessage(`Save failed: ${error.error || 'Unknown error'}`);
      }
    } catch (error) {
      setErrorMessage(`Save failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setSaving(false);
    }
  };

  // ── Undo / redo ────────────────────────────────────────────────────────────

  const addToHistory = (newForm: Partial<CMSRelease>) => {
    const newHistory = history.slice(0, historyIndex + 1);
    newHistory.push(JSON.parse(JSON.stringify(newForm)));
    setHistory(newHistory);
    setHistoryIndex(newHistory.length - 1);
  };

  const undo = () => {
    if (historyIndex > 0) { const idx = historyIndex - 1; setForm(JSON.parse(JSON.stringify(history[idx]))); setHistoryIndex(idx); }
  };

  const redo = () => {
    if (historyIndex < history.length - 1) { const idx = historyIndex + 1; setForm(JSON.parse(JSON.stringify(history[idx]))); setHistoryIndex(idx); }
  };

  // ── Language helpers ───────────────────────────────────────────────────────

  const getLanguageLabel = (code: string): string => {
    if (form.languageLabels?.[code]) return form.languageLabels[code];
    const preset = ALL_LANGUAGES.find((l) => l.code === code);
    if (preset) return preset.label;
    const custom = (form.customLanguages || []).find((l) => l.code === code);
    if (custom) return custom.label;
    return code.toUpperCase();
  };

  const normalizeLanguageCode = (raw: string) =>
    raw.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

  const addCustomLanguage = (code: string, label: string): boolean => {
    if (!code || !label) { setErrorMessage('Enter both language code and language name.'); return false; }
    if (!/^[a-z][a-z0-9-]{1,14}$/.test(code)) {
      setErrorMessage('Language code must start with a letter and use only lowercase letters, numbers, or dashes (2-15 chars).');
      return false;
    }
    const existing = [...ALL_LANGUAGES, ...(form.customLanguages || [])].find((l) => l.code === code);
    if (existing) { setErrorMessage(`Language code "${code}" already exists`); return false; }
    const newCustom = [...(form.customLanguages || []), { code, label }];
    const newAvailable = Array.from(new Set([...(form.availableLanguages || []), code]));
    setForm({ ...form, customLanguages: newCustom, availableLanguages: newAvailable, languageLabels: { ...(form.languageLabels || {}), [code]: label } });
    setSelectedSubtitleLanguage(code);
    setSelectedLyricsStructureLanguage(code);
    setReferenceLanguage(form.defaultLanguage || 'en');
    setErrorMessage(null);
    setSuccessMessage(`Added language ${label} (${code}) and activated it.`);
    return true;
  };

  const deleteCustomLanguage = (code: string) => {
    const newCustom = (form.customLanguages || []).filter((l) => l.code !== code);
    const newAvailable = (form.availableLanguages || []).filter((c) => c !== code);
    const defaultLang = form.defaultLanguage === code ? (newAvailable[0] || 'en') : form.defaultLanguage;
    setForm({ ...form, customLanguages: newCustom, availableLanguages: newAvailable, defaultLanguage: defaultLang });
    if (selectedSubtitleLanguage === code) setSelectedSubtitleLanguage(defaultLang || 'en');
    if (selectedLyricsStructureLanguage === code) setSelectedLyricsStructureLanguage(defaultLang || 'en');
    if (referenceLanguage === code) setReferenceLanguage(defaultLang || 'en');
    setSuccessMessage(`Removed custom language (${code}).`);
  };

  const saveLanguageLabel = (code: string, newLabel: string) => {
    setForm({ ...form, languageLabels: { ...(form.languageLabels || {}), [code]: newLabel.trim() } });
  };

  const setLanguageTone = (langCode: string, tone: string) => {
    setForm({ ...form, translationTone: { ...(form.translationTone || {}), [langCode]: tone } });
  };

  // ── Commentary / sponsors / credits ───────────────────────────────────────

  const updatePublicCommentary = (index: number, key: 'title' | 'content' | 'isPublished', value: string | boolean) => {
    const next = [...(form.publicCommentary || [])];
    if (!next[index]) return;
    next[index] = { ...next[index], [key]: value };
    setForm({ ...form, publicCommentary: next });
  };

  const addPublicCommentary = () => {
    setForm({ ...form, publicCommentary: [...(form.publicCommentary || []), { id: `commentary_${Date.now()}`, title: '', content: '', isPublished: true }] });
  };

  const removePublicCommentary = (index: number) => {
    const next = [...(form.publicCommentary || [])];
    next.splice(index, 1);
    setForm({ ...form, publicCommentary: next });
  };

  const updatePublicSponsor = (index: number, key: 'name' | 'role' | 'logoUrl' | 'isPublished', value: string | boolean) => {
    const next = [...(form.publicSponsors || [])];
    if (!next[index]) return;
    next[index] = { ...next[index], [key]: value };
    setForm({ ...form, publicSponsors: next });
  };

  const addPublicSponsor = () => {
    setForm({ ...form, publicSponsors: [...(form.publicSponsors || []), { id: `sponsor_${Date.now()}`, name: '', role: '', logoUrl: '', isPublished: true }] });
  };

  const removePublicSponsor = (index: number) => {
    const next = [...(form.publicSponsors || [])];
    next.splice(index, 1);
    setForm({ ...form, publicSponsors: next });
  };

  const updatePublicCredits = (section: 'artistic' | 'production' | 'visual' | 'literary' | 'rights', field: string, value: string) => {
    const credits = { ...(form.publicCredits || {}) } as Record<string, any>;
    const sectionData = { ...(credits[section] || {}), [field]: value };
    credits[section] = sectionData;
    setForm({ ...form, publicCredits: credits });
  };

  // ── Lyrics handlers ────────────────────────────────────────────────────────

  const getLyricsBlocks = (language: string) => {
    const structure = form.lyricsStructure || {};
    return Array.isArray(structure[language]) ? structure[language] : [];
  };

  const getPlaceholderSourceBlocks = (language: string) => {
    const blocks = getLyricsBlocks(language);
    if (!blocks.length) return [];
    if (lyricsPlaceholderScope === 'published') return blocks.filter((block: any) => block?.isPublished !== false);
    if (lyricsPlaceholderScope === 'single') {
      const picked = blocks.find((block: any) => String(block?.id || '') === lyricsPlaceholderBlockId);
      return picked ? [picked] : [];
    }
    return blocks;
  };

  const addLyricsBlock = () => {
    const language = selectedLyricsStructureLanguage || form.defaultLanguage || 'en';
    const structure = { ...(form.lyricsStructure || {}) } as Record<string, any[]>;
    const current = Array.isArray(structure[language]) ? [...structure[language]] : [];
    current.push({ id: `lyric_block_${Date.now()}`, type: 'verse', heading: '', lines: [], order: current.length + 1, isPublished: true });
    structure[language] = current;
    setForm({ ...form, lyricsStructure: structure });
  };

  const updateLyricsBlock = (index: number, key: 'type' | 'heading' | 'lines' | 'isPublished', value: string | boolean) => {
    const language = selectedLyricsStructureLanguage || form.defaultLanguage || 'en';
    const structure = { ...(form.lyricsStructure || {}) } as Record<string, any[]>;
    const current = Array.isArray(structure[language]) ? [...structure[language]] : [];
    if (!current[index]) return;
    if (key === 'lines') {
      current[index] = { ...current[index], lines: String(value || '').split('\n').map((line) => line.trim()).filter(Boolean) };
    } else {
      current[index] = { ...current[index], [key]: value };
    }
    structure[language] = current;
    setForm({ ...form, lyricsStructure: structure });
  };

  const removeLyricsBlock = (index: number) => {
    const language = selectedLyricsStructureLanguage || form.defaultLanguage || 'en';
    const structure = { ...(form.lyricsStructure || {}) } as Record<string, any[]>;
    const current = Array.isArray(structure[language]) ? [...structure[language]] : [];
    current.splice(index, 1);
    structure[language] = current.map((block, i) => ({ ...block, order: i + 1 }));
    setForm({ ...form, lyricsStructure: structure });
  };

  const syncLyricsLinesToCues = (lines: string[], sourceLanguage: string, targetLanguage: string, options?: { syncLineRef?: boolean }) => {
    const cleanLines = lines.map((line) => String(line || '').trim()).filter(Boolean);
    if (!cleanLines.length) {
      setLyricsPlaceholderNote('No placeholder lines detected. Add lines and try Apply again.');
      setErrorMessage('No placeholder lines to apply. Paste or load at least one lyric line.');
      return;
    }
    let subtitleCues = [...(form.subtitleCues || [])];
    const subtitleTranslations = { ...(form.subtitleTranslations || {}) } as Record<string, Record<string, string>>;
    subtitleTranslations[targetLanguage] = { ...(subtitleTranslations[targetLanguage] || {}) };
    const createdCount = Math.max(0, cleanLines.length - subtitleCues.length);
    if (subtitleCues.length < cleanLines.length) {
      const lastEnd = subtitleCues.length ? cueTimeToSeconds(subtitleCues[subtitleCues.length - 1].endTime) : 0;
      const missing = cleanLines.length - subtitleCues.length;
      for (let i = 0; i < missing; i += 1) {
        const cueNumber = subtitleCues.length + 1;
        const start = lastEnd + i * 3;
        subtitleCues.push({ id: `cue_${Date.now()}_${cueNumber}_${i}`, cueNumber, startTime: secondsToCueTime(start), endTime: secondsToCueTime(start + 3), lineRef: '', sourceType: 'manual', active: true });
      }
    }
    let assignedCount = 0;
    subtitleCues.forEach((cue, index) => {
      const placeholderText = cleanLines[index];
      if (!placeholderText) return;
      if (String(subtitleTranslations[targetLanguage]?.[cue.id] || '').trim() !== placeholderText) {
        subtitleTranslations[targetLanguage][cue.id] = placeholderText;
        assignedCount += 1;
      }
      if (options?.syncLineRef) cue.lineRef = `L${String(index + 1).padStart(3, '0')}`;
    });
    setForm({ ...form, subtitleCues, subtitleTranslations });
    setLyricsPlaceholderNote(`Applied ${assignedCount} line${assignedCount !== 1 ? 's' : ''} to ${getLanguageLabel(targetLanguage)} cues. Created ${createdCount} new cue${createdCount !== 1 ? 's' : ''}.`);
  };

  const loadLyricsIntoCuePlaceholders = () => {
    const sourceLanguage = selectedLyricsStructureLanguage || selectedSubtitleLanguage || form.defaultLanguage || 'en';
    const targetLanguage = selectedSubtitleLanguage || form.defaultLanguage || 'en';
    const allSourceBlocks = getLyricsBlocks(sourceLanguage);
    if (lyricsPlaceholderScope === 'single' && !lyricsPlaceholderBlockId && allSourceBlocks[0]?.id) setLyricsPlaceholderBlockId(String(allSourceBlocks[0].id));
    const sourceBlocks = getPlaceholderSourceBlocks(sourceLanguage);
    const fallbackBlocks = sourceLanguage === targetLanguage ? [] : getLyricsBlocks(targetLanguage);
    const lines = (sourceBlocks.length ? sourceBlocks : fallbackBlocks)
      .flatMap((block: any) => (Array.isArray(block.lines) ? block.lines : []))
      .map((line: string) => String(line || '').trim())
      .filter(Boolean);
    setLyricsPlaceholderOpen(true);
    if (!lines.length) {
      setLyricsPlaceholderDraft('');
      setLyricsPlaceholderNote(`No lines detected in ${getLanguageLabel(sourceLanguage)} lyrics blocks. Paste lines below or open Lyrics System Structure.`);
      return;
    }
    setLyricsPlaceholderDraft(lines.join('\n'));
    setLyricsPlaceholderNote(`Loaded ${lines.length} line${lines.length !== 1 ? 's' : ''} from ${sourceBlocks.length} block${sourceBlocks.length !== 1 ? 's' : ''} in ${getLanguageLabel(sourceLanguage)}. Click Apply to sync into ${getLanguageLabel(targetLanguage)} cues.`);
  };

  const applyLyricsPlaceholderDraft = () => {
    const sourceLanguage = selectedLyricsStructureLanguage || selectedSubtitleLanguage || form.defaultLanguage || 'en';
    const targetLanguage = selectedSubtitleLanguage || form.defaultLanguage || 'en';
    let lines = lyricsPlaceholderDraft.split('\n').map((line) => line.trim()).filter(Boolean);
    if (!lines.length) {
      const sourceBlocks = getPlaceholderSourceBlocks(sourceLanguage);
      const fallbackBlocks = sourceLanguage === targetLanguage ? [] : getLyricsBlocks(targetLanguage);
      lines = (sourceBlocks.length ? sourceBlocks : fallbackBlocks)
        .flatMap((block: any) => (Array.isArray(block.lines) ? block.lines : []))
        .map((line: string) => String(line || '').trim()).filter(Boolean);
      if (lines.length) {
        setLyricsPlaceholderDraft(lines.join('\n'));
        setLyricsPlaceholderNote(`Draft was empty, loaded ${lines.length} line${lines.length !== 1 ? 's' : ''} from lyrics blocks and applied.`);
      }
    }
    syncLyricsLinesToCues(lines, sourceLanguage, targetLanguage, { syncLineRef: lyricsPlaceholderSyncLineRef });
  };

  // ── Subtitle cue handlers ──────────────────────────────────────────────────

  const addCue = () => {
    const currentCues = form.subtitleCues || [];
    const cue = { id: `cue_${Date.now()}_${currentCues.length + 1}`, cueNumber: currentCues.length + 1, startTime: '00:00:00.000', endTime: '00:00:03.000', lineRef: '', sourceType: 'manual' as const, active: true };
    setForm({ ...form, subtitleCues: [...currentCues, cue] });
    setPreviewCueId(cue.id);
  };

  const updateCue = (cueId: string, field: string, value: string | number | boolean) => {
    setForm({ ...form, subtitleCues: (form.subtitleCues || []).map((cue) => cue.id === cueId ? { ...cue, [field]: value } : cue) });
  };

  const deleteCue = (cueId: string) => {
    const updatedCues = (form.subtitleCues || []).filter((cue) => cue.id !== cueId);
    const translations = { ...(form.subtitleTranslations || {}) };
    Object.keys(translations).forEach((lang) => { const m = { ...(translations[lang] || {}) }; delete m[cueId]; translations[lang] = m; });
    setForm({ ...form, subtitleCues: updatedCues, subtitleTranslations: translations });
    if (previewCueId === cueId) setPreviewCueId(updatedCues[0]?.id || null);
  };

  const setCueTranslation = (language: string, cueId: string, text: string) => {
    const translations = { ...(form.subtitleTranslations || {}) };
    const languageMap = { ...(translations[language] || {}), [cueId]: text };
    translations[language] = languageMap;
    const reviewStatus = { ...(form.translationReviewStatus || {}) };
    const langStatus = { ...(reviewStatus[language] || {}) };
    if (text.trim()) { if (langStatus[cueId] === 'ai') langStatus[cueId] = 'manual'; else if (!langStatus[cueId]) langStatus[cueId] = 'manual'; }
    reviewStatus[language] = langStatus;
    setForm({ ...form, subtitleTranslations: translations, translationReviewStatus: reviewStatus });
  };

  const acceptCueTranslation = (language: string, cueId: string) => {
    const reviewStatus = { ...(form.translationReviewStatus || {}) };
    reviewStatus[language] = { ...(reviewStatus[language] || {}), [cueId]: 'accepted' };
    setForm({ ...form, translationReviewStatus: reviewStatus });
  };

  const setCueMetadata = (cueId: string, patch: Record<string, any>) => {
    const metadata = { ...(form.subtitleCueMetadata || {}) } as Record<string, any>;
    metadata[cueId] = { ...(metadata[cueId] || {}), ...patch };
    setForm({ ...form, subtitleCueMetadata: metadata });
  };

  const applyCueMetadataToAllCues = (
    patch: Record<string, any>,
    options?: { clearPosition?: boolean; successMessage?: string; defaultStyleName?: string; defaultAlignment?: number; language?: string; }
  ) => {
    const cues = form.subtitleCues || [];
    if (!cues.length) {
      if (options?.defaultStyleName && options?.language) {
        const styleName = options.defaultStyleName;
        const alignment = Number(options.defaultAlignment || 2);
        const nextStylePacks = { ...(form.subtitleStylePacks || {}), [styleName]: { ...DEFAULT_STYLE_PACK, ...((form.subtitleStylePacks as Record<string, ASSStylePack> | undefined)?.[styleName] || {}), alignment } };
        const nextLanguageOverrides = { ...(form.languageStyleOverrides || {}), [options.language]: { ...((form.languageStyleOverrides as Record<string, any> | undefined)?.[options.language] || {}), stylePack: styleName } };
        setForm({ ...form, subtitleStylePacks: nextStylePacks, languageStyleOverrides: nextLanguageOverrides });
        setSuccessMessage(options.successMessage || `No cues yet. Applied ${styleName} as default style for ${options.language.toUpperCase()}.`);
        return;
      }
      if (options?.clearPosition) { setSuccessMessage(options.successMessage || 'No cue position overrides found to clear.'); return; }
      setErrorMessage('No cues available for batch update. Add or import cues first.');
      return;
    }
    const metadata = { ...(form.subtitleCueMetadata || {}) } as Record<string, any>;
    for (const cue of cues) {
      const next = { ...(metadata[cue.id] || {}), ...patch };
      if (options?.clearPosition) { delete next.positionX; delete next.positionY; }
      metadata[cue.id] = next;
    }
    setForm({ ...form, subtitleCueMetadata: metadata });
    if (options?.successMessage) setSuccessMessage(options.successMessage);
  };

  const setAllCuePositions = (positionX: number, positionY: number) => {
    const currentForm = liveRef.current.form;
    const cues = currentForm.subtitleCues || [];
    if (!cues.length) return;
    const metadata = { ...(currentForm.subtitleCueMetadata || {}) } as Record<string, any>;
    for (const cue of cues) metadata[cue.id] = { ...(metadata[cue.id] || {}), positionX, positionY };
    setForm({ ...currentForm, subtitleCueMetadata: metadata });
  };

  // ── Bulk cue operations ────────────────────────────────────────────────────

  const duplicateSelectedCues = () => {
    if (selectedCueIds.size === 0) { setErrorMessage('No cues selected'); return; }
    const cueList = form.subtitleCues || [];
    const newCues = cueList.filter((c) => selectedCueIds.has(c.id)).map((cue, idx) => ({
      ...cue, id: `cue_${Date.now()}_dup_${idx}`, endTime: secondsToCueTime(cueTimeToSeconds(cue.endTime) + 0.5),
    }));
    const updatedForm = { ...form, subtitleCues: [...cueList, ...newCues] };
    setForm(updatedForm);
    addToHistory(updatedForm);
    setSuccessMessage(`Duplicated ${selectedCueIds.size} cues`);
  };

  const deletSelectedCues = () => {
    if (selectedCueIds.size === 0) { setErrorMessage('No cues selected'); return; }
    const updatedForm = { ...form, subtitleCues: (form.subtitleCues || []).filter((c) => !selectedCueIds.has(c.id)) };
    setForm(updatedForm);
    addToHistory(updatedForm);
    setSelectedCueIds(new Set());
    setSuccessMessage(`Deleted ${selectedCueIds.size} cues`);
  };

  const deleteAllCues = () => {
    if (!confirm('Delete all cues? This cannot be undone.')) return;
    const updatedForm = { ...form, subtitleCues: [], subtitleTranslations: {} };
    setForm(updatedForm);
    addToHistory(updatedForm);
    setSelectedCueIds(new Set());
    setPreviewCueId(null);
    setSuccessMessage('Deleted all cues');
  };

  const shiftAllCueTiming = () => {
    if (shiftTimingOffset === 0) { setErrorMessage('Enter a time offset (in seconds)'); return; }
    const MIN_CUE_DURATION_SECONDS = 0.2;
    let clampedToZeroCount = 0, minDurationAdjustedCount = 0, overlapAdjustedCount = 0;
    let previousEnd = 0;

    const updated = (form.subtitleCues || []).map((cue) => {
      let start = cueTimeToSeconds(cue.startTime) + shiftTimingOffset;
      let end = cueTimeToSeconds(cue.endTime) + shiftTimingOffset;
      if (start < 0) { start = 0; clampedToZeroCount += 1; }
      if (end < 0) { end = 0; clampedToZeroCount += 1; }
      if (end <= start) { end = start + MIN_CUE_DURATION_SECONDS; minDurationAdjustedCount += 1; }
      if (start < previousEnd) { start = previousEnd; end = Math.max(end, start + MIN_CUE_DURATION_SECONDS); overlapAdjustedCount += 1; }
      previousEnd = end;
      return { ...cue, startTime: secondsToCueTime(start), endTime: secondsToCueTime(end) };
    });

    const updatedForm = { ...form, subtitleCues: updated };
    setForm(updatedForm);
    addToHistory(updatedForm);
    setShiftTimingOffset(0);

    const notes = [`Shifted ${updated.length} cues by ${shiftTimingOffset > 0 ? '+' : ''}${shiftTimingOffset}s.`];
    if (clampedToZeroCount > 0) notes.push(`${clampedToZeroCount} timestamp${clampedToZeroCount !== 1 ? 's' : ''} clamped to 0.`);
    if (minDurationAdjustedCount > 0) notes.push(`${minDurationAdjustedCount} cue${minDurationAdjustedCount !== 1 ? 's' : ''} stretched to minimum duration.`);
    if (overlapAdjustedCount > 0) notes.push(`${overlapAdjustedCount} overlap${overlapAdjustedCount !== 1 ? 's' : ''} resolved.`);
    setSuccessMessage(notes.join(' '));
  };

  const applyKaraokeToAllCues = () => {
    const cueCount = (form.subtitleCues || []).length;
    if (!cueCount) { setErrorMessage('No cues available for karaoke batch update.'); return; }
    applyCueMetadataToAllCues(
      { karaokeEffect: bulkKaraokeEffect, karaokeDurationsMs: bulkKaraokeEffect === 'none' ? '' : bulkKaraokeDurationsMs.trim() },
      { successMessage: bulkKaraokeEffect === 'none' ? `Cleared karaoke effect on ${cueCount} cue${cueCount !== 1 ? 's' : ''}.` : `Applied ${bulkKaraokeEffect.toUpperCase()} karaoke effect to ${cueCount} cue${cueCount !== 1 ? 's' : ''}.` }
    );
  };

  // ── Style pack handlers ────────────────────────────────────────────────────

  const updateStylePack = (styleName: string, patch: Partial<ASSStylePack>) => {
    const stylePacks = { ...(form.subtitleStylePacks || {}), [styleName]: { ...DEFAULT_STYLE_PACK, ...((form.subtitleStylePacks || {})[styleName] || {}), ...patch } };
    setForm({ ...form, subtitleStylePacks: stylePacks });
  };

  const addStylePack = () => {
    const nextName = `Style_${Date.now()}`;
    setForm({ ...form, subtitleStylePacks: { ...(form.subtitleStylePacks || {}), [nextName]: { ...DEFAULT_STYLE_PACK } } });
    setSelectedStyleName(nextName);
  };

  const removeStylePack = (styleName: string) => {
    if (styleName === DEFAULT_STYLE_NAME) return;
    const stylePacks = { ...(form.subtitleStylePacks || {}) } as Record<string, ASSStylePack>;
    delete stylePacks[styleName];
    const metadata = { ...(form.subtitleCueMetadata || {}) } as Record<string, any>;
    Object.keys(metadata).forEach((cueId) => { if (metadata[cueId]?.styleName === styleName) metadata[cueId] = { ...metadata[cueId], styleName: DEFAULT_STYLE_NAME }; });
    setForm({ ...form, subtitleStylePacks: Object.keys(stylePacks).length ? stylePacks : { [DEFAULT_STYLE_NAME]: { ...DEFAULT_STYLE_PACK } }, subtitleCueMetadata: metadata });
    setSelectedStyleName(DEFAULT_STYLE_NAME);
  };

  const setLanguageStylePack = (language: string, stylePack: string) => {
    const overrides = { ...(form.languageStyleOverrides || {}) } as Record<string, any>;
    overrides[language] = { ...(overrides[language] || {}), stylePack };
    setForm({ ...form, languageStyleOverrides: overrides });
  };

  // ── Language status / assignments ──────────────────────────────────────────

  const setLanguageStatus = (language: string, status: SubtitleStatus) => {
    setForm({ ...form, subtitleLanguageStatuses: { ...(form.subtitleLanguageStatuses || {}), [language]: status } });
  };

  const setLanguageAssignee = (language: string, role: 'translator' | 'reviewer', value: string) => {
    const assignments = { ...(form.subtitleLanguageAssignments || {}) };
    assignments[language] = { ...(assignments[language] || {}), [role]: value };
    setForm({ ...form, subtitleLanguageAssignments: assignments });
  };

  const addReviewLog = () => {
    const status = form.subtitleLanguageStatuses?.[selectedSubtitleLanguage] || 'draft';
    setForm({ ...form, subtitleReviewLogs: [...(form.subtitleReviewLogs || []), { id: `review_${Date.now()}`, language: selectedSubtitleLanguage, status, comment: reviewComment.trim(), actor: reviewActor.trim() || 'Editorial Admin', createdAt: new Date().toISOString() }] });
    setReviewComment('');
  };

  // ── Auto translate ─────────────────────────────────────────────────────────

  const autoTranslateLanguage = async (targetLang: string) => {
    const cues = form.subtitleCues || [];
    if (!cues.length) { setErrorMessage('No subtitle cues to translate. Add cues first.'); return; }
    const masterLang = form.defaultLanguage || 'en';
    if (targetLang === masterLang) { setErrorMessage('Target language is the same as the master language.'); return; }

    // Guard: warn before overwriting a reviewed/published language
    const langStatus = form.subtitleLanguageStatuses?.[targetLang];
    if (langStatus === 'verified' || langStatus === 'published') {
      const langLabel = getLanguageLabel(targetLang);
      const ok = window.confirm(
        `"${langLabel}" is currently ${langStatus}.\n\nAI translation will overwrite unaccepted cues. Accepted cues are always preserved.\n\nContinue?`
      );
      if (!ok) return;
    }

    // Guard: block if any cue has a malformed timestamp
    const badTimestampCues = cues.filter((c) => !Number.isFinite(cueTimeToSeconds(c.startTime)) || !Number.isFinite(cueTimeToSeconds(c.endTime)));
    if (badTimestampCues.length > 0) {
      setErrorMessage(`${badTimestampCues.length} cue${badTimestampCues.length !== 1 ? 's' : ''} have invalid timestamps (cue #${badTimestampCues.map((c) => c.cueNumber).join(', #')}). Fix before translating.`);
      return;
    }

    const sourceTexts = cues.map((cue) => form.subtitleTranslations?.[masterLang]?.[cue.id] || cue.lineRef || '');
    if (!sourceTexts.some((t) => t.trim().length > 0)) {
      setErrorMessage(`No text found in master language "${getLanguageLabel(masterLang)}" cues. Fill in subtitle text first.`);
      return;
    }

    // Warn (soft) if some cues have no master text — those will be skipped silently
    const emptyCueCount = sourceTexts.filter((t) => !t.trim()).length;
    if (emptyCueCount > 0) {
      const ok = window.confirm(
        `${emptyCueCount} cue${emptyCueCount !== 1 ? 's' : ''} have no master text and will be skipped.\n\nProceed with the ${cues.length - emptyCueCount} cue${cues.length - emptyCueCount !== 1 ? 's' : ''} that have text?`
      );
      if (!ok) return;
    }

    setAutoTranslatingLang(targetLang);
    try {
      const res = await fetch('/api/translate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        // tone intentionally omitted — plain machine translation until Phase 3 (LLM rewriting layer)
        body: JSON.stringify({ texts: sourceTexts, sourceLang: masterLang, targetLang }),
      });
      if (!res.ok) { const err = await res.json() as { error?: string }; throw new Error(err.error || 'Translation request failed'); }
      const { translations } = await res.json() as { translations: string[] };
      const translationsMap = { ...(form.subtitleTranslations || {}) };
      const langMap = { ...(translationsMap[targetLang] || {}) };
      const reviewStatus = { ...(form.translationReviewStatus || {}) };
      const currentLangStatus = { ...(reviewStatus[targetLang] || {}) };
      let written = 0;
      let skipped = 0;
      cues.forEach((cue, i) => {
        if (currentLangStatus[cue.id] === 'accepted') { skipped++; return; }
        if (translations[i]?.trim()) { langMap[cue.id] = translations[i]; currentLangStatus[cue.id] = 'ai'; written++; }
      });
      translationsMap[targetLang] = langMap;
      reviewStatus[targetLang] = currentLangStatus;
      setForm({ ...form, subtitleTranslations: translationsMap, translationReviewStatus: reviewStatus });
      const skippedNote = skipped > 0 ? ` (${skipped} accepted cue${skipped !== 1 ? 's' : ''} preserved)` : '';
      setSuccessMessage(`Auto-translated ${written} cue${written !== 1 ? 's' : ''} to ${getLanguageLabel(targetLang)}${skippedNote}`);
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'Auto-translation failed');
    } finally {
      setAutoTranslatingLang(null);
    }
  };

  // ── Import ─────────────────────────────────────────────────────────────────

  const handleImportSubtitleFile = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const lowerName = file.name.toLowerCase();
    const format: 'srt' | 'vtt' | 'ass' | null = lowerName.endsWith('.srt') ? 'srt' : lowerName.endsWith('.vtt') ? 'vtt' : lowerName.endsWith('.ass') ? 'ass' : null;
    if (!format) { setErrorMessage('Please upload .srt, .vtt, or .ass file.'); event.target.value = ''; return; }
    const content = await file.text();
    const parsed = format === 'ass' ? parseAssFile(content) : parseSubtitleFile(content, format);
    const importedStylePacks = format === 'ass' ? parseAssStyles(content) : {};
    if (!parsed.length) { setErrorMessage('No cues detected in subtitle file.'); event.target.value = ''; return; }
    const existingCueCount = (form.subtitleCues || []).length;
    if (existingCueCount > 0) {
      const ok = window.confirm(`Import will replace all ${existingCueCount} existing cue${existingCueCount !== 1 ? 's' : ''} with ${parsed.length} cue${parsed.length !== 1 ? 's' : ''} from "${file.name}".\n\nThis cannot be undone after save. Continue?`);
      if (!ok) { event.target.value = ''; return; }
    }
    const subtitleCues = parsed.map((cue, index) => ({ id: `cue_${Date.now()}_${index + 1}`, cueNumber: cue.cueNumber, startTime: cue.startTime, endTime: cue.endTime, lineRef: '', sourceType: format, active: true }));
    const cueMetadata = { ...(form.subtitleCueMetadata || {}) };
    if (format === 'ass') {
      subtitleCues.forEach((cue, idx) => {
        const source = parsed[idx] as any;
        cueMetadata[cue.id] = { ...(cueMetadata[cue.id] || {}), styleName: source.styleName || 'Mystic_Default', alignment: Number.isFinite(source.alignment) ? source.alignment : undefined, positionX: Number.isFinite(source.positionX) ? source.positionX : undefined, positionY: Number.isFinite(source.positionY) ? source.positionY : undefined };
      });
    }
    const subtitleTranslations = { ...(form.subtitleTranslations || {}), [selectedSubtitleLanguage]: {} as Record<string, string> };
    subtitleCues.forEach((cue, idx) => { subtitleTranslations[selectedSubtitleLanguage][cue.id] = parsed[idx]?.text || ''; });
    setForm({ ...form, subtitleCues, subtitleTranslations, masterAssSource: format === 'ass' ? content : (form.masterAssSource || ''), subtitleCueMetadata: cueMetadata, subtitleStylePacks: format === 'ass' && Object.keys(importedStylePacks).length ? importedStylePacks : (form.subtitleStylePacks || { [DEFAULT_STYLE_NAME]: { ...DEFAULT_STYLE_PACK } }), masterTimingVersion: (form.masterTimingVersion || 1) + 1 });
    setPreviewCueId(subtitleCues[0]?.id || null);
    if (format === 'ass') setSelectedStyleName(Object.keys(importedStylePacks)[0] || DEFAULT_STYLE_NAME);
    event.target.value = '';
  };

  // ── Preview drag / resize ──────────────────────────────────────────────────

  const handlePreviewDrag = (event: React.PointerEvent<HTMLDivElement>, cueId?: string) => {
    const canvas = previewCanvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    if (!rect.width || !rect.height) return;
    const updatePosition = (clientX: number, clientY: number) => {
      const x = Number(Math.max(0, Math.min(100, ((clientX - rect.left) / rect.width) * 100)).toFixed(2));
      const y = Number(Math.max(0, Math.min(100, ((clientY - rect.top) / rect.height) * 100)).toFixed(2));
      const { lockAllCuePositions: lockNow } = liveRef.current;
      if (cueId) { if (lockNow) { setAllCuePositions(x, y); } else { setCueMetadata(cueId, { positionX: x, positionY: y }); } }
      else { setPreviewPanelPosition({ x, y }); }
    };
    event.preventDefault();
    const target = event.currentTarget;
    target.setPointerCapture(event.pointerId);
    updatePosition(event.clientX, event.clientY);
    const move = (ev: PointerEvent) => updatePosition(ev.clientX, ev.clientY);
    const stop = () => { target.releasePointerCapture(event.pointerId); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', stop);
  };

  const handlePreviewInfoDrag = (event: React.PointerEvent<HTMLDivElement>) => {
    const canvas = previewCanvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    if (!rect.width || !rect.height) return;
    const updatePosition = (clientX: number, clientY: number) => {
      const x = ((clientX - rect.left) / rect.width) * 100;
      const y = ((clientY - rect.top) / rect.height) * 100;
      const halfWidthPercent = (previewInfoWidth / rect.width) * 50;
      const minX = Math.max(1, halfWidthPercent), maxX = Math.min(99, 100 - halfWidthPercent);
      setPreviewInfoPosition({ x: Number(Math.max(minX, Math.min(maxX, x)).toFixed(2)), y: Number(Math.max(3, Math.min(97, y)).toFixed(2)) });
    };
    event.preventDefault(); event.stopPropagation();
    const target = event.currentTarget;
    target.setPointerCapture(event.pointerId);
    updatePosition(event.clientX, event.clientY);
    const move = (ev: PointerEvent) => updatePosition(ev.clientX, ev.clientY);
    const stop = () => { target.releasePointerCapture(event.pointerId); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop);
  };

  const handlePreviewInfoResize = (event: React.PointerEvent<HTMLDivElement>, edge: 'left' | 'right') => {
    const canvas = previewCanvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    if (!rect.width) return;
    const startX = event.clientX, startWidth = previewInfoWidth;
    const updateWidth = (clientX: number) => {
      const nextWidth = edge === 'right' ? startWidth + (clientX - startX) : startWidth - (clientX - startX);
      const maxWidth = Math.max(220, rect.width - 8);
      const clampedWidth = Number(Math.max(160, Math.min(maxWidth, nextWidth)).toFixed(1));
      setPreviewInfoWidth(clampedWidth);
      setPreviewInfoPosition((prev) => {
        const halfWidthPercent = (clampedWidth / rect.width) * 50;
        const minX = Math.max(1, halfWidthPercent), maxX = Math.min(99, 100 - halfWidthPercent);
        return { ...prev, x: Number(Math.max(minX, Math.min(maxX, prev.x)).toFixed(2)) };
      });
    };
    event.preventDefault(); event.stopPropagation();
    const target = event.currentTarget;
    target.setPointerCapture(event.pointerId);
    updateWidth(event.clientX);
    const move = (ev: PointerEvent) => updateWidth(ev.clientX);
    const stop = () => { target.releasePointerCapture(event.pointerId); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop);
  };

  const handlePreviewResize = (event: React.PointerEvent<HTMLDivElement>, styleName: string, edge: 'left' | 'right' = 'right') => {
    const canvas = previewCanvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    if (!rect.width) return;
    const currentPack = (form.subtitleStylePacks || {})[styleName] || DEFAULT_STYLE_PACK;
    const startWidth = Number(currentPack.maxWidthPercent || DEFAULT_STYLE_PACK.maxWidthPercent || 82);
    const startX = event.clientX;
    const updateWidthFromClientX = (clientX: number) => {
      const deltaPercent = ((clientX - startX) / rect.width) * 200;
      const widthPercent = edge === 'right' ? startWidth + deltaPercent : startWidth - deltaPercent;
      updateStylePack(styleName, { maxWidthPercent: Number(Math.max(30, Math.min(200, widthPercent)).toFixed(2)) });
    };
    event.preventDefault(); event.stopPropagation();
    const target = event.currentTarget;
    target.setPointerCapture(event.pointerId);
    updateWidthFromClientX(event.clientX);
    const move = (ev: PointerEvent) => updateWidthFromClientX(ev.clientX);
    const stop = () => { target.releasePointerCapture(event.pointerId); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop);
  };

  // ── Timeline scrubbing ─────────────────────────────────────────────────────

  const scrubTimelineAtClientX = (clientX: number, duration: number) => {
    if (!timelineRef.current) return;
    const rect = timelineRef.current.getBoundingClientRect();
    if (!rect.width) return;
    const newTime = Number((Math.max(0, Math.min(1, (clientX - rect.left) / rect.width)) * Math.max(0, Number(duration || 0))).toFixed(3));
    setPreviewTime(newTime);
    if (/^[A-Za-z0-9_-]{11}$/.test(String(form.youtubeId || ''))) sendPreviewYouTubeCommand('seekTo', [newTime, true]);
  };

  const handleTimelineClick = (e: React.MouseEvent<HTMLDivElement>, duration: number) => scrubTimelineAtClientX(e.clientX, duration);

  const handleTimelinePointerDown = (e: React.PointerEvent<HTMLDivElement>, duration: number) => {
    e.preventDefault();
    scrubTimelineAtClientX(e.clientX, duration);
    const move = (ev: PointerEvent) => scrubTimelineAtClientX(ev.clientX, duration);
    const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop);
  };

  // ── YouTube helpers ────────────────────────────────────────────────────────

  const sendPreviewYouTubeCommand = (func: string, args: Array<string | number | boolean> = []) => {
    const targetWindow = previewYouTubeIframeRef.current?.contentWindow;
    if (!targetWindow) return;
    targetWindow.postMessage(JSON.stringify({ event: 'command', func, args }), '*');
  };

  const bootstrapPreviewYouTubePlayer = () => {
    setPreviewYouTubeReady(true);
    window.setTimeout(() => {
      sendPreviewYouTubeCommand('addEventListener', ['onReady']);
      sendPreviewYouTubeCommand('addEventListener', ['onStateChange']);
      sendPreviewYouTubeCommand('addEventListener', ['infoDelivery']);
      sendPreviewYouTubeCommand('getDuration');
    }, 120);
  };

  // ── Export / delivery ──────────────────────────────────────────────────────

  const buildSubtitleExportUrl = (language: string, format: 'srt' | 'vtt' | 'ass') =>
    `/api/releases/${releaseId}/subtitles?${new URLSearchParams({ lang: language, format }).toString()}`;

  const getSubtitleExportLanguages = () =>
    Array.from(new Set([...(form.availableLanguages || []), ...Object.keys(form.subtitleTranslations || {}), selectedSubtitleLanguage])).filter(Boolean);

  const getTrackMeta = (language: string): CaptionTrackMeta =>
    ((form.youtubeCaptionTracks as Record<string, CaptionTrackMeta> | undefined)?.[language] || {}) as CaptionTrackMeta;

  const suggestReadinessState = (sourceForm: Partial<CMSRelease>, trackOverride?: Record<string, CaptionTrackMeta>): ContentReadinessState => {
    const status = sourceForm.status || 'draft';
    if (status === 'draft') return 'draft';
    if (status === 'in_review' || status === 'approved') return 'editorial_ready';
    if (status !== 'published') return 'delivery_attention_required';
    const tracks = (trackOverride || sourceForm.youtubeCaptionTracks || {}) as Record<string, CaptionTrackMeta>;
    const languageSet = new Set<string>([...(sourceForm.availableLanguages || []), ...Object.keys(sourceForm.subtitleTranslations || {}), ...Object.keys(tracks)].filter(Boolean));
    if (!languageSet.size) return 'web_published';
    const states = Array.from(languageSet).map((language) => (tracks[language] || {}).deliveryState || 'web_only');
    if (states.some((s) => s === 'sync_failed')) return 'delivery_attention_required';
    if (states.every((s) => s === 'synced_to_youtube' || s === 'manual_upload_completed')) return 'fully_delivered';
    return states.some((s) => s === 'synced_to_youtube' || s === 'manual_upload_pending' || s === 'manual_upload_completed') ? 'youtube_delivery_in_progress' : 'web_published';
  };

  const persistDeliveryTracks = async (tracks: Record<string, CaptionTrackMeta>, readinessState: ContentReadinessState, successText?: string) => {
    if (isNew || !releaseId) { setSuccessMessage('Delivery state updated locally. Save release to persist.'); return; }
    try {
      const response = await fetch(`/api/releases/${releaseId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ youtubeCaptionTracks: tracks, contentReadinessState: readinessState }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data?.error || 'Failed to persist delivery state');
      if (successText) setSuccessMessage(successText);
    } catch (error: any) {
      setErrorMessage(`Delivery state persistence failed: ${error?.message || 'Unknown error'}`);
    }
  };

  const persistReleasePatch = async (patch: Partial<CMSRelease>, successText?: string) => {
    if (isNew || !releaseId) { setSuccessMessage('Saved locally. Create release first to persist this control.'); return; }
    try {
      const response = await fetch(`/api/releases/${releaseId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) });
      const data = await response.json();
      if (!response.ok) throw new Error(data?.error || 'Failed to persist release settings');
      setForm((previous) => ({ ...previous, ...patch }));
      if (successText) setSuccessMessage(successText);
    } catch (error: any) {
      setErrorMessage(`Failed to persist release settings: ${error?.message || 'Unknown error'}`);
    }
  };

  const toggleWebPublishState = async () => {
    const nextStatus = form.status === 'published' ? 'unpublished' : 'published';
    await persistReleasePatch({ status: nextStatus, contentReadinessState: suggestReadinessState({ ...form, status: nextStatus }) }, `Web status set to ${nextStatus}.`);
  };

  const updateReadinessState = async (nextReadiness: ContentReadinessState) => {
    await persistReleasePatch({ contentReadinessState: nextReadiness }, `Readiness updated to ${nextReadiness.replace(/_/g, ' ')}.`);
  };

  const updateTrackMeta = (language: string, patch: Partial<CaptionTrackMeta>, options?: { persist?: boolean; successText?: string }) => {
    const tracks = { ...(form.youtubeCaptionTracks || {}) } as Record<string, CaptionTrackMeta>;
    tracks[language] = { ...(tracks[language] || {}), language, ...patch };
    const nextReadiness = suggestReadinessState(form, tracks);
    setForm((previous) => ({ ...previous, youtubeCaptionTracks: tracks, contentReadinessState: nextReadiness }));
    if (options?.persist) void persistDeliveryTracks(tracks, nextReadiness, options.successText);
  };

  const markManualDeliveryState = (language: string, state: Extract<DeliveryState, 'manual_upload_pending' | 'manual_upload_completed'>) => {
    updateTrackMeta(language, { deliveryState: state, manualUploadActor, manualUploadAt: new Date().toISOString(), manualUploadNotes: manualUploadNotes[language] || '' }, {
      persist: true,
      successText: `${language.toUpperCase()} marked as ${state === 'manual_upload_pending' ? 'manual upload pending' : 'manual upload completed'}.`,
    });
  };

  const exportSubtitleByLanguage = async (language: string, format: 'srt' | 'vtt' | 'ass') => {
    if (isNew) { setErrorMessage('Save this release before exporting subtitle files.'); return; }
    try {
      const response = await fetch(buildSubtitleExportUrl(language, format));
      if (!response.ok) throw new Error(`Export failed for ${language.toUpperCase()} ${format.toUpperCase()}`);
      const blob = await response.blob();
      const fallback = `${form.slug || releaseId}-${language}.${format}`;
      triggerBlobDownload(blob, extractFilenameFromDisposition(response.headers.get('content-disposition'), fallback));
      updateTrackMeta(language, { lastExportedAt: new Date().toISOString() }, { persist: true, successText: `${language.toUpperCase()} ${format.toUpperCase()} export telemetry saved.` });
    } catch (error) {
      console.error(error);
      setErrorMessage('Subtitle export failed. Please try again.');
    }
  };

  const exportAllSubtitlesZip = async () => {
    if (isNew) { setErrorMessage('Save this release before exporting subtitle files.'); return; }
    const languages = getSubtitleExportLanguages();
    if (!languages.length) { setErrorMessage('No subtitle languages available to export.'); return; }
    setExportingZip(true);
    try {
      const zip = new JSZip();
      const failed: string[] = [];
      for (const language of languages) {
        for (const format of ['srt', 'vtt', 'ass'] as const) {
          try {
            const response = await fetch(buildSubtitleExportUrl(language, format));
            if (!response.ok) { failed.push(`${language.toUpperCase()} ${format.toUpperCase()}`); continue; }
            const fallback = `${form.slug || releaseId}-${language}.${format}`;
            zip.file(extractFilenameFromDisposition(response.headers.get('content-disposition'), fallback), await response.arrayBuffer());
          } catch (error) { console.error(error); failed.push(`${language.toUpperCase()} ${format.toUpperCase()}`); }
        }
      }
      if (!Object.keys(zip.files).length) { setErrorMessage('No subtitle files were generated for ZIP export.'); return; }
      triggerBlobDownload(await zip.generateAsync({ type: 'blob' }), `${form.slug || releaseId}-subtitles-srt-vtt-ass.zip`);
      const exportedAt = new Date().toISOString();
      const tracks = { ...(form.youtubeCaptionTracks || {}) } as Record<string, CaptionTrackMeta>;
      for (const language of languages) tracks[language] = { ...(tracks[language] || {}), language, lastExportedAt: exportedAt };
      const nextReadiness = suggestReadinessState(form, tracks);
      setForm((previous) => ({ ...previous, youtubeCaptionTracks: tracks, contentReadinessState: nextReadiness }));
      await persistDeliveryTracks(tracks, nextReadiness, 'ZIP export telemetry saved.');
      if (failed.length) setErrorMessage(`ZIP exported with partial results. Failed: ${failed.join(', ')}`);
    } catch (error) {
      console.error(error);
      setErrorMessage('Failed to export subtitle ZIP. Please try again.');
    } finally {
      setExportingZip(false);
    }
  };

  const syncYouTubeSubtitles = async (options?: { releaseId?: string; mode?: 'update-changed' | 'force-update'; languages?: string[]; silent?: boolean }) => {
    const targetReleaseId = options?.releaseId || releaseId;
    if (!targetReleaseId || targetReleaseId === 'new') {
      if (!options?.silent) setErrorMessage('Save this release before syncing subtitles to YouTube.');
      return null;
    }
    setYoutubeSyncing(true);
    try {
      const response = await fetch(`/api/releases/${targetReleaseId}/youtube-subtitles`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: options?.mode || 'update-changed', format: 'srt', isDraft: false, languages: options?.languages?.length ? options.languages : getSubtitleExportLanguages(), youtubeSubtitleAutoSync: form.youtubeSubtitleAutoSync !== false }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data?.error || 'YouTube subtitle sync failed');
      setForm((previous) => {
        const nextTracks = { ...(previous.youtubeCaptionTracks || {}), ...(data.youtubeCaptionTracks || {}) } as Record<string, CaptionTrackMeta>;
        const attemptAt = new Date().toISOString();
        for (const row of Array.isArray(data?.results) ? data.results : []) {
          const language = String(row?.language || '').trim();
          if (!language) continue;
          const status = String(row?.status || '').toLowerCase();
          const current = nextTracks[language] || {};
          const nextState: DeliveryState = status === 'failed' ? 'sync_failed' : (status === 'inserted' || status === 'updated' || status === 'skipped') ? 'synced_to_youtube' : (current.deliveryState || 'web_only');
          nextTracks[language] = { ...current, language, lastSyncAttemptAt: attemptAt, deliveryState: nextState };
        }
        return { ...previous, youtubeCaptionTracks: nextTracks, contentReadinessState: suggestReadinessState(previous, nextTracks) };
      });
      if (!options?.silent) setSuccessMessage(`YouTube subtitle sync complete\nSuccess: ${data.successCount} | Skipped: ${data.skippedCount} | Failed: ${data.failedCount}`);
      return data;
    } catch (error: any) {
      if (!options?.silent) setErrorMessage(`YouTube subtitle sync failed: ${error?.message || 'Unknown error'}`);
      return null;
    } finally {
      setYoutubeSyncing(false);
    }
  };

  const openPublicReleasePreview = () => {
    const slug = String(form.slug || '').trim();
    if (!slug) { setErrorMessage('Add a slug first to preview the public release URL.'); return; }
    if (typeof window !== 'undefined') window.open(`/release-detail/${encodeURIComponent(slug)}`, '_blank', 'noopener,noreferrer');
  };

  const copySubtitleNamingConvention = async () => {
    const slug = String(form.slug || '').trim() || releaseId;
    const text = ['Subtitle naming convention:', `${slug}-{language}.srt`, `${slug}-{language}.vtt`, `${slug}-{language}.ass`].join('\n');
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard) { await navigator.clipboard.writeText(text); setSuccessMessage('Subtitle naming convention copied to clipboard.'); return; }
      setErrorMessage('Clipboard is unavailable in this browser context.');
    } catch { setErrorMessage('Could not copy naming convention.'); }
  };

  // ── Workflow helpers ───────────────────────────────────────────────────────

  const scrollToSection = (sectionId: string) => {
    if (typeof document === 'undefined') return;
    document.getElementById(sectionId)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const runWorkflowAction = (sectionId: string) => {
    if (sectionId === 'lyrics-structure-section') {
      const activeLanguage = selectedLyricsStructureLanguage || form.defaultLanguage || 'en';
      if (getLyricsBlocks(activeLanguage).length === 0) addLyricsBlock();
      scrollToSection(sectionId);
      return;
    }
    if (sectionId === 'subtitle-timeline-section') {
      if ((form.subtitleCues || []).length === 0) addCue();
      else loadLyricsIntoCuePlaceholders();
      scrollToSection(sectionId);
      return;
    }
    scrollToSection(sectionId);
  };

  // ── Return ─────────────────────────────────────────────────────────────────

  return {
    // Core form
    form, setForm,
    originalForm, setOriginalForm,
    hasUnsavedChanges,
    loading, notFound,
    saving,
    activeTab, setActiveTab,
    exportingZip,
    youtubeSyncing,
    errorMessage, setErrorMessage,
    successMessage, setSuccessMessage,
    fieldErrors,
    slugAutoGenerated,
    carryForwardNotice, setCarryForwardNotice,

    // Refs
    previewCanvasRef,
    previewYouTubeIframeRef,
    timelineRef,
    liveRef,

    // Language UI
    selectedSubtitleLanguage, setSelectedSubtitleLanguage,
    selectedLyricsStructureLanguage, setSelectedLyricsStructureLanguage,
    referenceLanguage, setReferenceLanguage,
    sideBySideMode, setSideBySideMode,
    selectedStyleName, setSelectedStyleName,
    autoTranslatingLang,

    // Preview
    previewCueId, setPreviewCueId,
    previewPanelPosition,
    previewInfoPosition,
    previewInfoWidth,
    previewCanvasWidth,
    previewTime, setPreviewTime,
    previewPlaying, setPreviewPlaying,
    lockAllCuePositions, setLockAllCuePositions,
    previewVideoDuration, setPreviewVideoDuration,
    previewOrigin,
    showSafeGuides, setShowSafeGuides,
    autoAdvanceAfterStamp, setAutoAdvanceAfterStamp,

    // Review / delivery
    reviewActor, setReviewActor,
    reviewComment, setReviewComment,
    manualUploadActor, setManualUploadActor,
    manualUploadNotes, setManualUploadNotes,

    // Bulk cues
    selectedCueIds, setSelectedCueIds,
    shiftTimingOffset, setShiftTimingOffset,
    bulkKaraokeEffect, setBulkKaraokeEffect,
    bulkKaraokeDurationsMs, setBulkKaraokeDurationsMs,

    // Lyrics placeholder
    lyricsPlaceholderOpen, setLyricsPlaceholderOpen,
    lyricsPlaceholderDraft, setLyricsPlaceholderDraft,
    lyricsPlaceholderNote,
    lyricsPlaceholderScope, setLyricsPlaceholderScope,
    lyricsPlaceholderBlockId, setLyricsPlaceholderBlockId,
    lyricsPlaceholderSyncLineRef, setLyricsPlaceholderSyncLineRef,

    // YouTube integration
    youtubeIntegrationStatus,
    fetchedYouTubeChannel,
    youtubeChannelLookupLoading,

    // Workflow
    expandedWorkflowStepId, setExpandedWorkflowStepId,

    // Core handlers
    loadRelease,
    handleSave,
    handleSubmit,
    handleInputChange,
    handleCheckboxChange,
    generateSlug,
    handleYouTubePaste,
    applyFetchedChannelDefaults,
    applyCarryForwardToCurrentForm,
    clearAutosave,
    recoverAutosave,

    // Lyrics
    getLyricsBlocks,
    getPlaceholderSourceBlocks,
    syncLyricsLinesToCues,
    addLyricsBlock,
    updateLyricsBlock,
    removeLyricsBlock,
    loadLyricsIntoCuePlaceholders,
    applyLyricsPlaceholderDraft,

    // Subtitle cues
    addCue,
    updateCue,
    deleteCue,
    setCueTranslation,
    acceptCueTranslation,
    setCueMetadata,
    applyCueMetadataToAllCues,
    duplicateSelectedCues,
    deletSelectedCues,
    deleteAllCues,
    shiftAllCueTiming,
    applyKaraokeToAllCues,

    // Style packs
    updateStylePack,
    addStylePack,
    removeStylePack,
    setLanguageStylePack,

    // Language management
    getLanguageLabel,
    normalizeLanguageCode,
    addCustomLanguage,
    deleteCustomLanguage,
    saveLanguageLabel,
    setLanguageTone,

    // Language status / assignments
    setLanguageStatus,
    setLanguageAssignee,
    addReviewLog,

    // Translation
    autoTranslateLanguage,

    // Import
    handleImportSubtitleFile,

    // Preview interactions
    sendPreviewYouTubeCommand,
    bootstrapPreviewYouTubePlayer,
    handlePreviewDrag,
    handlePreviewInfoDrag,
    handlePreviewInfoResize,
    handlePreviewResize,
    handleTimelineClick,
    handleTimelinePointerDown,

    // Commentary / sponsors / credits
    addPublicCommentary,
    updatePublicCommentary,
    removePublicCommentary,
    addPublicSponsor,
    updatePublicSponsor,
    removePublicSponsor,
    updatePublicCredits,

    // Export / delivery
    buildSubtitleExportUrl,
    getSubtitleExportLanguages,
    getTrackMeta,
    suggestReadinessState,
    persistDeliveryTracks,
    persistReleasePatch,
    toggleWebPublishState,
    updateReadinessState,
    updateTrackMeta,
    markManualDeliveryState,
    exportSubtitleByLanguage,
    exportAllSubtitlesZip,
    syncYouTubeSubtitles,
    openPublicReleasePreview,
    copySubtitleNamingConvention,

    // Workflow
    scrollToSection,
    runWorkflowAction,

    // Undo / redo
    addToHistory,
    undo,
    redo,
  };
}
