const fs = require('fs');
const path = require('path');

const corePath = path.join(__dirname, '../.data/constitutional_core.json');
const registryPath = path.join(__dirname, '../.data/knowledge-registry.json');
const relsPath = path.join(__dirname, '../.data/atlas_relationships.json');

const core = JSON.parse(fs.readFileSync(corePath, 'utf8'));
const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
const rels = JSON.parse(fs.readFileSync(relsPath, 'utf8'));

const newPersons = [
  {
    "id": "person_ahmad_sirhindi",
    "type": "saint",
    "slug": "ahmad-sirhindi",
    "name": "Ahmad Sirhindi",
    "alternateNames": ["Mujaddid Alf Thani", "Shaykh Ahmad Sirhindi"],
    "shortDescription": "Major Naqshbandi reformer known as the Mujaddid (Reviver) of the second Islamic millennium.",
    "longDescription": "Ahmad Sirhindi (1564–1624 CE) was an Indian Islamic scholar, Hanafi jurist, and a prominent member of the Naqshbandi Sufi order. He is widely recognized as 'Mujaddid Alf Thani', meaning the 'reviver of the second millennium', for his work in rejuvenating Islam and opposing the syncretic religious movement Din-i Ilahi instituted by the Mughal Emperor Akbar. Sirhindi's most significant theological contribution was his concept of Wahdat al-Shuhud (Unity of Witnessing), which he articulated as a correction to the prevailing doctrine of Wahdat al-Wujud (Unity of Being) associated with Ibn Arabi. He asserted that the creator and creation are separate, and that mystical unity is an experience of the seeker rather than an ontological reality.",
    "theologicalNotes": "His doctrine of Wahdat al-Shuhud emphasized strict adherence to Sharia and the separation between the Divine and the created, reshaping the theological landscape of South Asian Sufism.",
    "regionLinks": ["in", "pk"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["wahdat_al_shuhud", "sharia", "naqshbandi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Ahmad_Sirhindi"],
    "wikidataId": "Q401083",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 2
  },
  {
    "id": "person_hasan_al_basri",
    "type": "saint",
    "slug": "hasan-al-basri",
    "name": "Hasan al-Basri",
    "alternateNames": ["Al-Hasan al-Basri"],
    "shortDescription": "Foundational ascetic and spiritual authority in early Islam.",
    "longDescription": "Hasan al-Basri (642–728 CE) was an early Muslim preacher, ascetic, theologian, exegete, scholar, judge, and mystic. Born in Medina, he later settled in Basra, Iraq. He is considered one of the most important figures of the generation following the companions of the Prophet (the Tabi'un). Hasan's spirituality was characterized by a profound fear of God (taqwa) and a strict asceticism (zuhd). His sermons often warned against the distractions of the worldly life and the imminence of the hereafter. He is a central figure in the spiritual genealogies (silsilas) of numerous Sufi orders, serving as a crucial link between the early Islamic period and the later formalized Sufi traditions.",
    "theologicalNotes": "His teachings laid the foundation for the 'sober' tradition of Sufism, deeply rooted in ethical purity, constant sorrow for one's shortcomings, and rigorous self-examination.",
    "regionLinks": ["iq", "sa"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["zuhd", "taqwa", "wara"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Hasan_al-Basri"],
    "wikidataId": "Q312948",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  },
  {
    "id": "person_ibrahim_ibn_adham",
    "type": "saint",
    "slug": "ibrahim-ibn-adham",
    "name": "Ibrahim ibn Adham",
    "alternateNames": ["Abou Ben Adhem", "Ibrahim bin Adham"],
    "shortDescription": "Iconic prince-turned-mystic who renounced his throne for the ascetic path.",
    "longDescription": "Ibrahim ibn Adham (718–782 CE) is one of the most celebrated early Sufi ascetics. According to legend, he was the king of Balkh (in modern-day Afghanistan) who abandoned his throne, wealth, and family to pursue a life of spiritual poverty and devotion to God. His story is often compared to that of the Buddha. A famous anecdote recounts his awakening: while hunting, an unseen voice or a deer spoke to him, asking if he was created for this pastime. This triggered a profound conversion. He lived the rest of his life as a wandering laborer, exemplifying the virtues of Tawakkul (trust in God) and Zuhd (renunciation).",
    "theologicalNotes": "He embodied the archetype of the royal ascetic, demonstrating that true kingship belongs only to God, and the highest human attainment is chosen poverty and absolute reliance on the Divine.",
    "regionLinks": ["af", "sy"],
    "languageLinks": ["ar", "fa"],
    "relatedConcepts": ["zuhd", "tawakkul", "faqr"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Ibrahim_ibn_Adham"],
    "wikidataId": "Q1379766",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 2
  },
  {
    "id": "person_jami",
    "type": "poet",
    "slug": "jami",
    "name": "Jami",
    "alternateNames": ["Nur al-Din Abd al-Rahman Jami", "Mawlana Jami"],
    "shortDescription": "One of the greatest Persian Sufi poets and a leading scholar of the Naqshbandi order.",
    "longDescription": "Nur al-Din Abd al-Rahman Jami (1414–1492 CE) was a prolific Persian scholar, poet, and mystic from Herat (modern-day Afghanistan). He is often regarded as the last great classical poet of the Persian tradition. A devout member of the Naqshbandi order, Jami seamlessly blended profound mystical philosophy with exquisite poetic expression. His works include 'Haft Awrang' (The Seven Thrones), 'Baharistan', and 'Nafahat al-Uns' (a biographical dictionary of saints). Jami was also a major proponent and interpreter of Ibn Arabi's doctrine of Wahdat al-Wujud, making complex philosophical concepts accessible through his allegorical poetry, particularly in his masterpiece 'Yusuf and Zulaikha'.",
    "theologicalNotes": "Jami's work represents a sophisticated synthesis of Naqshbandi spiritual discipline, Ibn Arabi's metaphysics of Unity, and the classical Persian poetic tradition.",
    "regionLinks": ["af", "ir"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["wahdat_al_wujud", "naqshbandi", "ishq"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Jami"],
    "wikidataId": "Q312411",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 2
  },
  {
    "id": "person_khwaja_ahrar",
    "type": "saint",
    "slug": "khwaja-ahrar",
    "name": "Khwaja Ahrar",
    "alternateNames": ["Nasir al-Din Ubaydullah Ahrar"],
    "shortDescription": "Leading Naqshbandi master of Central Asia who wielded immense political and spiritual influence.",
    "longDescription": "Khwaja Ahrar (1404–1490 CE) was a pivotal figure in the Naqshbandi Sufi order. Based in Samarqand, he transformed the order into a major social and political force in Central Asia. Unlike ascetics who withdrew from the world, Khwaja Ahrar actively engaged with Timurid rulers, using his immense wealth and influence to protect the common people from unjust taxation and oppression. He believed that the role of the spiritual guide was not just to nurture disciples, but to ensure justice in society by advising and guiding rulers. Under his leadership, the Naqshbandi network expanded vastly.",
    "theologicalNotes": "He embodied the Naqshbandi principle of 'Khalwat dar Anjuman' (solitude in the crowd), demonstrating that high spiritual states could be maintained while holding significant worldly power and engaging in political affairs.",
    "regionLinks": ["uz", "af"],
    "languageLinks": ["fa", "tr"],
    "relatedConcepts": ["naqshbandi", "khalwat_dar_anjuman"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Khwaja_Ahrar"],
    "wikidataId": "Q6403330",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 1
  },
  {
    "id": "person_rabia_balkhi",
    "type": "poet",
    "slug": "rabia-balkhi",
    "name": "Rabia Balkhi",
    "alternateNames": ["Rabia Quzdari", "Rabia of Balkh"],
    "shortDescription": "Early Persian mystical poet known for her tragic life and passionate poetry.",
    "longDescription": "Rabia Balkhi (10th century CE) is considered the first female poet in the history of New Persian literature. Born into a royal family in Balkh, she fell deeply in love with a Turkic slave named Bektash. Her poetry, which expressed this intense, forbidden love, eventually led to her downfall. According to legend, when her brother (the king) discovered her romance, he ordered her to be imprisoned in a hot bathhouse with her veins slit. She supposedly wrote her final poems on the walls with her own blood before dying. In the Sufi tradition, her earthly love for Bektash is often interpreted as an allegory for the soul's desperate, all-consuming longing for God.",
    "theologicalNotes": "Her life and work blur the lines between 'Ishq-e-Majazi' (metaphorical/earthly love) and 'Ishq-e-Haqiqi' (true/divine love), a recurring theme in Persian mystic poetry.",
    "regionLinks": ["af", "ir"],
    "languageLinks": ["fa"],
    "relatedConcepts": ["ishq", "fana"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Rabia_Balkhi"],
    "wikidataId": "Q445657",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 90,
    "evidenceRecords": 2
  },
  {
    "id": "person_saadi_shirazi",
    "type": "poet",
    "slug": "saadi-shirazi",
    "name": "Saadi Shirazi",
    "alternateNames": ["Saadi", "Abū-Muḥammad Muṣliḥ al-Dīn bin Abdallāh Shīrāzī"],
    "shortDescription": "Globally known Persian poet whose works combine profound wisdom, ethical teachings, and Sufi themes.",
    "longDescription": "Saadi Shirazi (1210–1291 CE) is one of the greatest poets of the classical Persian tradition. He traveled extensively across the Islamic world after the Mongol invasions disrupted life in Persia. His experiences yielded profound insights into human nature, which he immortalized in his two masterworks: the 'Bustan' (The Orchard), written entirely in verse, and the 'Gulistan' (The Rose Garden), a mix of prose and poetry. While not exclusively a Sufi poet like Rumi or Attar, Saadi's works are deeply infused with Islamic ethics, practical wisdom, and mystical reflections. He is celebrated for the simplicity, elegance, and universal appeal of his language.",
    "theologicalNotes": "Saadi's Sufism is eminently practical and ethical. He emphasized compassion, humility, and the brotherhood of all humanity, famously declaring that all human beings are members of a single body.",
    "regionLinks": ["ir", "af", "in"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["akhlaq", "ihsan", "adab"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Saadi_Shirazi"],
    "wikidataId": "Q170302",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 97,
    "evidenceRecords": 2
  },
  {
    "id": "person_safi_al_din",
    "type": "saint",
    "slug": "sheikh-safi-al-din-ardabili",
    "name": "Sheikh Safi al-Din Ardabili",
    "alternateNames": ["Safi-ad-din Ardabili"],
    "shortDescription": "Eponymous founder of the Safaviyya order, which later established the Safavid Empire.",
    "longDescription": "Sheikh Safi al-Din Ardabili (1252–1334 CE) was a Kurdish-Persian Sufi master from Ardabil. He was a disciple of Sheikh Zahed Gilani, whom he succeeded as the head of the Zahediyeh order, which was subsequently renamed the Safaviyya in his honor. Sheikh Safi al-Din was renowned for his piety, charisma, and organizational skills, attracting a massive following across Iran, Anatolia, and the Caucasus. While he was a Sunni Shafi'i, his descendants gradually militarized the order and adopted Twelver Shi'ism, eventually leading to the foundation of the Safavid Empire by Shah Ismail I. His shrine in Ardabil is a masterpiece of Persian architecture.",
    "theologicalNotes": "He emphasized rigorous spiritual discipline, ethical purity, and deep devotion. His historical significance lies in how a peaceful Sufi order evolved into a major political and imperial force.",
    "regionLinks": ["ir", "az", "tr"],
    "languageLinks": ["fa", "az", "ar"],
    "relatedConcepts": ["safaviyya", "tariqa", "wilayah"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Safi-ad-din_Ardabili"],
    "wikidataId": "Q982701",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 91,
    "evidenceRecords": 1
  },
  {
    "id": "person_uways_al_qarani",
    "type": "saint",
    "slug": "uways-al-qarani",
    "name": "Uways al-Qarani",
    "alternateNames": ["Owais al-Qarani"],
    "shortDescription": "Legendary early saint who attained deep spiritual connection with the Prophet despite never meeting him.",
    "longDescription": "Uways al-Qarani (d. 657 CE) was a contemporary of the Prophet Muhammad living in Yemen. He represents a unique archetype in Sufism: the hidden saint who achieves the highest spiritual stations without physical proximity to a master. Uways desperately wanted to meet the Prophet, but chose to stay in Yemen to care for his blind, elderly mother. Despite never meeting physically, the Prophet praised Uways highly and instructed his companions Umar and Ali to seek him out and ask for his prayers. Uways died fighting in the Battle of Siffin. The term 'Uwaysi' is now used in Sufism to describe seekers who receive spiritual initiation and guidance from a master who is physically absent or deceased.",
    "theologicalNotes": "He is the namesake of the 'Uwaysi' transmission method, proving that spiritual connection (Rabita) transcends physical time and space.",
    "regionLinks": ["ye", "iq"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["uwaysi", "rabita", "birr"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Uwais_al-Qarani"],
    "wikidataId": "Q927708",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 2
  },
  {
    "id": "person_zunnun",
    "type": "saint",
    "slug": "zunnun-al-misri",
    "name": "Zunnun al-Misri",
    "alternateNames": ["Dhul-Nun al-Misri", "Thawban ibn Ibrahim"],
    "shortDescription": "Early Egyptian Sufi master who introduced the concept of spiritual gnosis (Marifa).",
    "longDescription": "Zunnun al-Misri (796–859 CE) was an early Egyptian Sufi and ascetic born in Akhmim, Upper Egypt. He is widely credited with introducing the systematic teaching of Marifa (spiritual gnosis or inner knowledge), distinguishing it from Ilm (intellectual or discursive knowledge). According to legends, he could decipher ancient Egyptian hieroglyphs and was familiar with hermetic traditions. Zunnun's teachings focused intensely on the inner mysteries of the soul and the transformative power of divine love. His poetic utterances laid the groundwork for the ecstatic Sufi poetry that would follow in later centuries.",
    "theologicalNotes": "He categorized knowledge into three types: the knowledge of the masses (theology), the knowledge of philosophers/scientists, and the highest knowledge—Marifa—granted directly by God to the hearts of the saints.",
    "regionLinks": ["eg", "iq"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["marifa", "ilm", "gnosis"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Dhul-Nun_al-Misri"],
    "wikidataId": "Q1207865",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 2
  },
  {
    "id": "person_sahl_tustari",
    "type": "saint",
    "slug": "sahl-al-tustari",
    "name": "Sahl al-Tustari",
    "alternateNames": ["Sahl ibn 'Abd Allah al-Tustari"],
    "shortDescription": "Influential mystical theologian and early Sufi exegete.",
    "longDescription": "Sahl al-Tustari (818–896 CE) was an early Persian Sufi master and Quranic exegete from Shushtar. He is renowned for his esoteric commentary on the Quran (Tafsir al-Tustari) and his deep psychological insights into the nature of the ego (nafs). He practiced extreme asceticism, fasting continuously for days. Tustari's teachings heavily influenced later giants of Sufism, including Mansur al-Hallaj, who was his disciple for a time. He introduced the concept of the 'Muhammadan Light' (Nur Muhammad), asserting that the pre-existent light of the Prophet was the first creation of God, a doctrine that became central to later Sufi cosmology.",
    "theologicalNotes": "His doctrine emphasized continuous repentance (Tawba) and the fierce battle against the lower self (Nafs). He formulated the metaphysics of the Nur Muhammad.",
    "regionLinks": ["ir", "iq"],
    "languageLinks": ["ar", "fa"],
    "relatedConcepts": ["nur_muhammad", "tafseer", "nafs"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Sahl_al-Tustari"],
    "wikidataId": "Q2212030",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 91,
    "evidenceRecords": 1
  },
  {
    "id": "person_hakim_tirmidhi",
    "type": "scholar",
    "slug": "hakim-al-tirmidhi",
    "name": "Hakim al-Tirmidhi",
    "alternateNames": ["Al-Hakim al-Tirmidhi"],
    "shortDescription": "Architect of the theory of sainthood (Wilayah) in Sufism.",
    "longDescription": "Al-Hakim al-Tirmidhi (d. 869 CE) was an early Islamic mystic and scholar from Termez (modern-day Uzbekistan). He is most famous for his pioneering work 'Khatm al-Awliya' (The Seal of the Saints). In this text, he systematically laid out the hierarchy of saints, drawing a parallel between prophethood (Nubuwwah) and sainthood (Wilayah). He argued that just as there is a Seal of the Prophets (Muhammad), there must be a Seal of the Saints who sits at the pinnacle of the spiritual hierarchy. This theory profoundly influenced Ibn Arabi, who later expanded on it. Tirmidhi's works blend psychological introspection, hadith scholarship, and mystical philosophy.",
    "theologicalNotes": "He developed a rigorous terminology for the hierarchy of saints (Awliya, Abdal, Qutb) and distinguished between the outward performance of religion and the inner light of spiritual certitude.",
    "regionLinks": ["uz", "ir"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["wilayah", "khatm_al_awliya", "qutb"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Al-Hakim_al-Tirmidhi"],
    "wikidataId": "Q300628",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 1
  },
  {
    "id": "person_abdullah_ansari",
    "type": "poet",
    "slug": "abdullah-ansari-of-herat",
    "name": "Abdullah Ansari of Herat",
    "alternateNames": ["Khwaja Abdullah Ansari", "Pir-i Herat"],
    "shortDescription": "Famous Persian mystic and poet, known as the Sage of Herat.",
    "longDescription": "Khwaja Abdullah Ansari (1006–1089 CE) was a Persian Sufi saint, Hanbali scholar, and poet born in Herat (modern-day Afghanistan). Affectionately known as 'Pir-i Herat' (The Sage of Herat), he is celebrated for his exquisite rhythmic prose (saj') and poetry. His masterpiece, 'Munajat' (Intimate Conversations with God), remains one of the most beloved texts in Persian literature, filled with passionate, poetic prayers. Ansari was also a rigorous theologian who wrote 'Manazil al-Sairin' (Stations of the Wayfarers), a systematic guide detailing the hundred stages of the spiritual path. He successfully bridged strict orthodox theology with profound mystical devotion.",
    "theologicalNotes": "His works synthesize Hanbali traditionalism with ecstatic Sufi devotion, providing a structured map of the soul's ascent through ethical and spiritual stations.",
    "regionLinks": ["af", "ir"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["munajat", "manazil", "ihsan"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Khwaja_Abdullah_Ansari"],
    "wikidataId": "Q1370295",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 2
  },
  {
    "id": "person_jili",
    "type": "scholar",
    "slug": "abd-al-karim-al-jili",
    "name": "Abd al-Karim al-Jili",
    "alternateNames": ["Al-Jili"],
    "shortDescription": "Author of 'The Perfect Human' and leading expositor of Ibn Arabi's thought.",
    "longDescription": "Abd al-Karim al-Jili (1365–1424 CE) was a Sufi mystic and scholar, born in Jilan (Iran) or perhaps Calicut (India), and a spiritual descendant of Abdul Qadir Gilani. He is best known as one of the foremost interpreters of Ibn Arabi's philosophy. Al-Jili's seminal work, 'Al-Insan al-Kamil' (The Perfect Human), is a masterwork of Sufi metaphysics. It clarifies and systemizes Ibn Arabi's complex doctrines, explaining how God, whose essence is unknowable, reveals Himself through His names and attributes, which are ultimately perfectly reflected in the 'Perfect Human'—the cosmic archetype whose primary manifestation is the Prophet Muhammad.",
    "theologicalNotes": "Al-Jili articulated a cosmology where existence is a process of divine descent and human ascent. The Insan al-Kamil acts as the mirror in which God sees Himself.",
    "regionLinks": ["ir", "ye", "in"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["insan_al_kamil", "wahdat_al_wujud", "tajalli"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Abd_al-Karim_al-Jili"],
    "wikidataId": "Q2820908",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 1
  },
  {
    "id": "person_shah_waliullah",
    "type": "scholar",
    "slug": "shah-waliullah-dehlawi",
    "name": "Shah Waliullah Dehlawi",
    "alternateNames": ["Shah Waliullah", "Qutb-ud-Din Ahmad al-Faruqi"],
    "shortDescription": "Major spiritual reformer who synthesized diverse Islamic disciplines and Sufi schools in India.",
    "longDescription": "Shah Waliullah Dehlawi (1703–1762 CE) was an Islamic scholar, reformer, and Sufi master in the Indian subcontinent. Living during the decline of the Mughal Empire, he sought to revitalize Muslim society by synthesizing competing intellectual and spiritual traditions. A master of several Sufi orders (including the Naqshbandi and Qadiri), he worked to reconcile the seemingly opposed doctrines of Wahdat al-Wujud (Ibn Arabi's Unity of Being) and Wahdat al-Shuhud (Ahmad Sirhindi's Unity of Witnessing), arguing that the differences were merely semantic. His magnum opus, 'Hujjat Allah al-Baligha', remains a foundational text of Islamic sociology and theology.",
    "theologicalNotes": "His synthesis brought intellectual harmony to South Asian Sufism, asserting that both Wujud and Shuhud are valid perspectives of the same divine reality at different stages of realization.",
    "regionLinks": ["in", "pk"],
    "languageLinks": ["ar", "fa", "ur"],
    "relatedConcepts": ["wahdat_al_wujud", "wahdat_al_shuhud", "islah"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Shah_Waliullah_Dehlawi"],
    "wikidataId": "Q31245",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 2
  },
  {
    "id": "person_muhammad_ghawth",
    "type": "saint",
    "slug": "muhammad-ghawth",
    "name": "Muhammad Ghawth",
    "alternateNames": ["Shah Muhammad Ghouth Gwaliori"],
    "shortDescription": "Influential Indian Sufi master of the Shattariyya order, known for integrating yogic practices.",
    "longDescription": "Muhammad Ghawth of Gwalior (1500–1562 CE) was a highly influential Sufi master of the Shattari order in 16th-century India. He enjoyed the patronage of Mughal Emperors Babur, Humayun, and Akbar. He is notable for his deep engagement with local Indian spiritual traditions. In his work 'Bahr al-Hayat' (The Ocean of Life), he translated and adapted Hindu yogic practices and mantras into a Sufi framework, emphasizing the universality of mystical truth. He was also a mentor to the legendary musician Tansen, heavily influencing the development of Hindustani classical music. His magnificent tomb in Gwalior remains a major architectural and spiritual landmark.",
    "theologicalNotes": "The Shattari method involves a rapid, ecstatic ascent to God. Ghawth's integration of breath control and yogic postures (asanas) demonstrates the syncretic nature of Indian Sufism.",
    "regionLinks": ["in"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["shattari", "yoga", "sama"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Muhammad_Ghawth"],
    "wikidataId": "Q16201272",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 91,
    "evidenceRecords": 1
  },
  {
    "id": "person_lal_shahbaz",
    "type": "saint",
    "slug": "lal-shahbaz-qalandar",
    "name": "Lal Shahbaz Qalandar",
    "alternateNames": ["Syed Usman Marwandi", "Jhulelal"],
    "shortDescription": "Revered saint across South Asia, famous for his ecstatic 'qalandari' path and widespread devotion.",
    "longDescription": "Syed Usman Marwandi (1177–1274 CE), universally known as Lal Shahbaz Qalandar, was a Sufi saint and poet born in Maiwand, Afghanistan, who eventually settled in Sehwan, Sindh (modern-day Pakistan). He belonged to the Qalandariyya order, characterized by wandering ascetics who often rejected societal norms to maintain uninterrupted connection with God. He is highly revered by Muslims and Hindus alike, often syncretized with the deity Jhulelal. His shrine in Sehwan Sharif is the site of massive, ecstatic Dhamal (Sufi dance) gatherings. The famous qawwali 'Dama Dam Mast Qalandar' is an enduring tribute to his spiritual legacy.",
    "theologicalNotes": "The Qalandari path emphasizes absolute, intoxicating love for God (Masti), often disregarding outward formalities in favor of internal ecstasy and radical detachment from the world.",
    "regionLinks": ["pk", "in", "af"],
    "languageLinks": ["fa", "sd", "ur"],
    "relatedConcepts": ["qalandar", "dhamal", "masti"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Lal_Shahbaz_Qalandar"],
    "wikidataId": "Q2511210",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  },
  {
    "id": "person_sachal_sarmast",
    "type": "poet",
    "slug": "sachal-sarmast",
    "name": "Sachal Sarmast",
    "alternateNames": ["Abdul Wahab Farouqi", "Sachal", "Sarmast"],
    "shortDescription": "Celebrated Sindhi mystic poet known for his bold expressions of divine love and religious tolerance.",
    "longDescription": "Abdul Wahab Farouqi (1739–1829 CE), known by his pen names Sachal (The Truthful) and Sarmast (The Intoxicated), was a Sufi poet from Sindh. He composed poetry in seven languages, including Sindhi, Siraiki, Persian, and Urdu. Heavily influenced by Mansur al-Hallaj and Attar, his poetry is marked by a fearless, ecstatic expression of Wahdat al-Wujud (Unity of Being). He was a vehement critic of the religious establishment, mullahs, and empty rituals, preaching a message of universal love and humanism that bridged the Hindu-Muslim divide in Sindh. His shrine in Daraza is a major center of Sufi culture and music.",
    "theologicalNotes": "Like Hallaj, Sachal Sarmast frequently employed the language of 'Ana al-Haqq' (I am the Truth), viewing all religious distinctions as illusory veils covering the one divine reality.",
    "regionLinks": ["pk", "in"],
    "languageLinks": ["sd", "pa", "fa", "ur"],
    "relatedConcepts": ["wahdat_al_wujud", "sarmast", "ishq"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Sachal_Sarmast"],
    "wikidataId": "Q3053702",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 2
  },
  {
    "id": "person_waris_ali_shah",
    "type": "saint",
    "slug": "waris-ali-shah",
    "name": "Waris Ali Shah",
    "alternateNames": ["Haji Waris Ali Shah", "Sarkar Waris Pak"],
    "shortDescription": "Influential modern Sufi saint from Dewa Sharif whose universal message attracted diverse followers.",
    "longDescription": "Haji Waris Ali Shah (1817–1905 CE) was a Sufi saint from Dewa, Barabanki, India, and the founder of the Warsi order. He traveled extensively, reportedly performing the Hajj multiple times on foot and visiting Europe. His message was simple, centered entirely on universal love, famously stating: 'Jo Rab hai wahi Ram hai' (He who is God is also Ram). This deep syncretism and message of universal brotherhood attracted followers from across religious lines, including Muslims, Hindus, and Christians. His shrine in Dewa Sharif continues to host a major annual Urs, characterized by an atmosphere of joy, inclusivity, and communal harmony.",
    "theologicalNotes": "His teachings emphasized the universality of divine love (Ishq), stripping away dogmatic differences to focus on the essential unity of all spiritual seekers.",
    "regionLinks": ["in", "pk"],
    "languageLinks": ["ur", "hi"],
    "relatedConcepts": ["ishq", "sulh_i_kul", "warsi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Waris_Ali_Shah"],
    "wikidataId": "Q13010373",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 90,
    "evidenceRecords": 1
  },
  {
    "id": "person_shabistari",
    "type": "poet",
    "slug": "mahmud-shabistari",
    "name": "Mahmud Shabistari",
    "alternateNames": ["Mahmud-e Shabistari", "Sa'd al-Din Mahmud Shabistari"],
    "shortDescription": "Author of 'The Secret Rose Garden' (Gulshan-i Raz), a masterful poetic summary of Sufi metaphysics.",
    "longDescription": "Mahmud Shabistari (1288–1340 CE) was a Persian Sufi poet and scholar from Shabestar, near Tabriz. He is renowned almost entirely for his masterpiece, 'Gulshan-i Raz' (The Secret Rose Garden). Written in 1311 in response to a series of metaphysical questions posed by a Sufi master from Khorasan, this short verse treatise provides a highly concentrated, brilliantly systematic exposition of Ibn Arabi's doctrine of Wahdat al-Wujud (Unity of Being) using the symbolic language of Persian poetry (wine, tresses, idols, taverns). It became an indispensable textbook for later generations of Sufis, accompanied by numerous commentaries, most notably by Lahiji.",
    "theologicalNotes": "Shabistari decoded the lexicon of Persian mystical poetry, explaining how romantic and earthly metaphors represent the soul's journey, divine attributes, and the realization of Unity.",
    "regionLinks": ["ir", "af"],
    "languageLinks": ["fa"],
    "relatedConcepts": ["gulshan", "wahdat_al_wujud", "tajalli"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Mahmud_Shabistari"],
    "wikidataId": "Q1370291",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 2
  }
];

// Append missing persons to core if they aren't there
newPersons.forEach(p => {
  if (!core.find(c => c.slug === p.slug)) {
    core.push({
      "class": "persons",
      "slug": p.slug,
      "name": p.name,
      "aliases": p.alternateNames,
      "canonicalImpact": p.shortDescription,
      "readinessScore": p.knowledgeDensityScore,
      "resilienceScore": 90,
      "confidenceLayer": "High",
      "verificationStatus": "Verified",
      "evidenceRecords": p.evidenceRecords,
      "disputeStatus": "None",
      "relatedQuestions": []
    });
  }
});

// Add to registry
newPersons.forEach(p => {
  if (!registry.find(r => r.slug === p.slug || r.id === p.id)) {
    registry.push(p);
  }
});

fs.writeFileSync(corePath, JSON.stringify(core, null, 2));
fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));

console.log(`Enriched registry with ${newPersons.length} comprehensive figures.`);
