const fs = require('fs');
const path = require('path');

const corePath = path.join(__dirname, '../.data/constitutional_core.json');
const registryPath = path.join(__dirname, '../.data/knowledge-registry.json');
const relsPath = path.join(__dirname, '../.data/atlas_relationships.json');

const core = JSON.parse(fs.readFileSync(corePath, 'utf8'));
const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
const rels = JSON.parse(fs.readFileSync(relsPath, 'utf8'));

const newPersons = [
  {
    "id": "person_nund_rishi",
    "type": "saint",
    "slug": "nund-rishi",
    "name": "Nund Rishi",
    "alternateNames": ["Sheikh Noor-ud-Din Noorani", "Sahazanand", "Alamdar-e-Kashmir"],
    "shortDescription": "Founder of the Rishi order of Kashmir, revered universally as Alamdar-e-Kashmir.",
    "longDescription": "Nund Rishi (1377–1440 CE), formally known as Sheikh Noor-ud-Din Noorani, is the patron saint of Kashmir and the founder of the indigenous Rishi Sufi order. He successfully synthesized Islamic mysticism with the pre-existing ascetic traditions of Kashmir, drawing heavily from the asceticism of Lal Ded. His teachings, composed in Kashmiri verse known as 'Shruks', emphasize radical non-violence, strict vegetarianism, environmental conservation (famously stating 'Food will last as long as forests last'), and complete devotion to God over ritualism. His shrine in Charar-e-Sharief is one of the most sacred pilgrimage sites in Kashmir for both Muslims and Hindus.",
    "theologicalNotes": "His Rishi movement was uniquely Kashmiri, representing a deep, peaceful indigenization of Islam that emphasized ethical purity, severe asceticism, and universal brotherhood.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["rishi", "shruk", "ahimsa"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Nund_Rishi"],
    "wikidataId": "Q3346337",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 97,
    "evidenceRecords": 2
  },
  {
    "id": "person_lal_ded",
    "type": "poet",
    "slug": "lal-ded",
    "name": "Lal Ded",
    "alternateNames": ["Lalleshwari", "Lalla Arifa"],
    "shortDescription": "Mystic poet of Kashmir whose Vakhs form the foundation of Kashmiri literature and syncretic spirituality.",
    "longDescription": "Lal Ded (1320–1392 CE), also known as Lalleshwari or Lalla Arifa, was a Kashmiri mystic of the Kashmir Shaivism school who profoundly influenced Sufi saints like Nund Rishi. Escaping an abusive marriage, she renounced worldly life, wandering naked or semi-naked across the Kashmir Valley while reciting ecstatic mystic verses known as 'Vakhs'. Her verses brilliantly articulate the philosophy of non-dualism, criticizing idol worship and religious hypocrisy while urging the seeker to find the divine within their own heart. Muslims regard her as a Sufi saint, while Hindus revere her as a Shaivite yogini, making her the ultimate symbol of Kashmir's syncretic spiritual heritage (Kashmiriyat).",
    "theologicalNotes": "Her Vakhs emphasize the total dissolution of the ego and the realization of the absolute unity of all existence, transcending all sectarian divides.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["vakh", "kashmiriyat", "fana"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Lalleshwari"],
    "wikidataId": "Q2983770",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  },
  {
    "id": "person_mir_sayyid_ali_hamadani",
    "type": "saint",
    "slug": "mir-sayyid-ali-hamadani",
    "name": "Mir Sayyid Ali Hamadani",
    "alternateNames": ["Shah-e-Hamadan", "Amir-e-Kabir"],
    "shortDescription": "Persian Sufi master who played a monumental role in spreading Islam and Persian culture in Kashmir.",
    "longDescription": "Mir Sayyid Ali Hamadani (1314–1384 CE), reverently known in Kashmir as 'Shah-e-Hamadan' (King of Hamadan) and 'Amir-e-Kabir' (The Great Commander), was a prominent Persian Sufi of the Kubrawiya order. To escape the conquests of Timur, he migrated to Kashmir accompanied by 700 sayyids, scholars, and artisans. He is credited not only with the mass peaceful conversion of the Kashmiri population to Islam, but also with revolutionizing the region's economy by introducing Persian arts, crafts (like Pashmina weaving), and architecture. He authored over a hundred treatises on theology, ethics, and politics, bridging the spiritual and the societal.",
    "theologicalNotes": "His methodology focused intensely on 'Awrad' (daily litanies), particularly the Awrad-e-Fathiyya, while maintaining that a true Sufi must earn a lawful living and contribute to society rather than relying on charity.",
    "regionLinks": ["in_jk", "ir", "tj"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["kubrawiya", "awrad", "kasb"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Mir_Sayyid_Ali_Hamadani"],
    "wikidataId": "Q1393660",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 98,
    "evidenceRecords": 2
  },
  {
    "id": "person_hamza_makhdoom",
    "type": "saint",
    "slug": "sheikh-hamza-makhdoom",
    "name": "Sheikh Hamza Makhdoom",
    "alternateNames": ["Makhdoom Sahib", "Sultan-ul-Arifeen"],
    "shortDescription": "Prominent Sufi saint of the Suhrawardi order who fiercely combated orthodox rigidities in Kashmir.",
    "longDescription": "Sheikh Hamza Makhdoom (1494–1576 CE), popularly known as Makhdoom Sahib or Sultan-ul-Arifeen, was a towering Sufi saint of the Suhrawardi order in Kashmir. He played a critical role during the turbulent period of the Chak dynasty. Unlike the forest-dwelling Rishis, Makhdoom Sahib actively engaged with the masses in urban centers, establishing mosques and spreading education. He was known for his fierce opposition to both extreme orthodoxy and extreme asceticism, advocating instead for the middle path of the Sunnah. His shrine on Hari Parbat hill in Srinagar is one of the most prominent spiritual landmarks in the city.",
    "theologicalNotes": "He synthesized the ecstatic spirituality of the Suhrawardiyya with strict adherence to Sharia, functioning as a powerful moral compass during a period of intense political instability.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["fa", "ks"],
    "relatedConcepts": ["suhrawardi", "sharia", "sunnah"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Hamza_Makhdoom"],
    "wikidataId": "Q5646505",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 1
  },
  {
    "id": "person_baba_dawood_khaki",
    "type": "scholar",
    "slug": "baba-dawood-khaki",
    "name": "Baba Dawood Khaki",
    "alternateNames": ["Dawood Khaki"],
    "shortDescription": "Chief disciple of Makhdoom Sahib and a major scholar-saint of Kashmir.",
    "longDescription": "Baba Dawood Khaki was the foremost disciple and khalifa of Sheikh Hamza Makhdoom. A highly educated scholar, he gave up a prestigious bureaucratic position to become a Sufi dervish under Makhdoom Sahib's guidance. He traveled extensively across Kashmir to propagate the Suhrawardi order. He is celebrated for his immense literary contributions, authoring several significant works in Persian that documented the lives, miracles, and teachings of Kashmiri saints, including his masterpiece 'Wird-ul-Murideen', a comprehensive poetic tribute and spiritual guide.",
    "theologicalNotes": "His works served to canonize and formalize the teachings of the Suhrawardi order in Kashmir, providing a rigorous intellectual framework for its spiritual practices.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["suhrawardi", "wird"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Baba_Dawood_Khaki"],
    "wikidataId": "Q4837286",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 91,
    "evidenceRecords": 1
  },
  {
    "id": "person_payamuddin_reshi",
    "type": "saint",
    "slug": "baba-payamuddin-reshi",
    "name": "Baba Payamuddin Reshi",
    "alternateNames": ["Baba Reshi", "Payam-ud-Din"],
    "shortDescription": "Prominent disciple of Nund Rishi who renounced his wealth to serve the poor.",
    "longDescription": "Baba Payamuddin Reshi, affectionately known as Baba Reshi, was a prominent minister in the court of the ruler of Kashmir who renounced his power, wealth, and worldly status after a profound spiritual awakening. He became a devoted disciple of Nund Rishi (Sheikh Noor-ud-Din Noorani) and joined the Rishi order. He lived a life of extreme simplicity and service in the mountains near Gulmarg. His shrine in Tangmarg is deeply revered, famously known for granting the wishes of childless couples and serving food (langar) continuously to thousands of visitors.",
    "theologicalNotes": "His life epitomizes the core tenet of the Rishi order: the total renunciation of worldly power in exchange for serving humanity and contemplating the Divine in nature.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks", "fa"],
    "relatedConcepts": ["rishi", "langar", "tark"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Baba_Payamuddin_Reshi"],
    "wikidataId": "Q4837365",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 1
  },
  {
    "id": "person_zain_ud_din_wali",
    "type": "saint",
    "slug": "zain-ud-din-wali",
    "name": "Zain-ud-Din Wali",
    "alternateNames": ["Zainuddin Rishi", "Zia Singh"],
    "shortDescription": "Hindu prince who converted to Islam and became one of Nund Rishi's chief disciples.",
    "longDescription": "Zain-ud-Din Wali, originally a Rajput Hindu prince named Zia Singh from Kishtwar, fell gravely ill and was miraculously cured by Nund Rishi. Deeply moved, he embraced Islam, taking the name Zain-ud-Din, and became one of Nund Rishi's most prominent Khulafa (successors). He meditated for years in a cave in Aishmuqam, entirely detached from worldly affairs. His shrine in Aishmuqam is famous for the 'Zool' festival, where thousands of devotees light wooden torches in the evening to commemorate his spiritual illumination.",
    "theologicalNotes": "His spiritual journey represents the profound cross-cultural integration achieved by the Rishi movement, illustrating that spiritual enlightenment transcends birth and background.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["rishi", "zool"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Aishmuqam_Shrine"],
    "wikidataId": "Q123456",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 90,
    "evidenceRecords": 0
  },
  {
    "id": "person_bamuddin_rishi",
    "type": "saint",
    "slug": "bamuddin-rishi",
    "name": "Bamuddin Rishi",
    "alternateNames": ["Bhuma Sadhu", "Baba Bamuddin"],
    "shortDescription": "A highly respected Hindu ascetic who embraced the Rishi order of Islam.",
    "longDescription": "Bamuddin Rishi, originally known as Bhuma Sadhu, was a highly respected and powerful Hindu ascetic. He engaged in a profound spiritual dialogue and theological debate with Nund Rishi. Overwhelmed by Nund Rishi's spiritual presence and the depth of his Islamic mysticism, Bhuma Sadhu accepted Islam, took the name Bamuddin, and became a pillar of the Rishi order. His conversion was entirely intellectual and spiritual, highlighting the peaceful, dialogical nature of Islam's spread in Kashmir.",
    "theologicalNotes": "His inclusion in the Rishi canon demonstrates the intellectual rigor and profound experiential truth that the early Rishis possessed, capable of winning over advanced ascetics from other traditions.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["rishi", "dialogue"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 89,
    "evidenceRecords": 0
  },
  {
    "id": "person_nasib_ud_din",
    "type": "saint",
    "slug": "baba-nasib-ud-din-ghazi",
    "name": "Baba Nasib-ud-Din Ghazi",
    "alternateNames": ["Abul Fuqra"],
    "shortDescription": "Prolific builder of mosques and a tireless social worker in the Sufi tradition of Kashmir.",
    "longDescription": "Baba Nasib-ud-Din Ghazi was a prominent disciple of Baba Dawood Khaki. He is widely celebrated in Kashmiri history not just as a mystic, but as a legendary social worker and architect of community infrastructure. Often called 'Abul Fuqra' (Father of the Poor), he reportedly oversaw the construction of over 1,200 mosques, bathhouses, and bridges across the Kashmir valley to benefit the common people. He embodied the Sufi ideal that serving God is indistinguishable from serving humanity.",
    "theologicalNotes": "He perfectly integrated the Suhrawardi focus on inward purification with massive outward public works, creating a model of 'applied Sufism'.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["fa", "ks"],
    "relatedConcepts": ["khidma", "suhrawardi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 91,
    "evidenceRecords": 0
  },
  {
    "id": "person_bulbul_shah",
    "type": "saint",
    "slug": "bulbul-shah",
    "name": "Bulbul Shah",
    "alternateNames": ["Syed Sharafuddin Abdul Rahman"],
    "shortDescription": "The first Sufi saint to introduce Islam to Kashmir and initiate its ruler.",
    "longDescription": "Syed Sharafuddin Abdul Rahman, universally revered as Bulbul Shah, was a Suhrawardi Sufi saint from Turkestan. He holds the historical distinction of being the first major Islamic missionary to arrive in Kashmir in the early 14th century (predating Shah-e-Hamadan). Through his profound character and spiritual miracles, he successfully converted the Buddhist ruler of Kashmir, Rinchen Shah, to Islam (who took the name Sultan Sadur-ud-Din). This event marked the beginning of Kashmir's formal transition into an Islamic society. The first mosque in Kashmir was built for him along the banks of the Jhelum river.",
    "theologicalNotes": "Bulbul Shah established the first formal Sufi presence (Suhrawardiyya) in Kashmir, setting a precedent of peaceful, character-based proselytization.",
    "regionLinks": ["in_jk", "uz"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["suhrawardi", "dawah"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Bulbul_Shah"],
    "wikidataId": "Q4996078",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 1
  },
  {
    "id": "person_jalaluddin_bukhari_kashmir",
    "type": "saint",
    "slug": "syed-jalaluddin-bukhari",
    "name": "Syed Jalaluddin Bukhari",
    "alternateNames": ["Makhdoom Jahaniyan Jahangasht"],
    "shortDescription": "World-traveling Sufi saint whose teachings influenced the spiritual landscape of the subcontinent, including Kashmir.",
    "longDescription": "Syed Jalaluddin Surkh-Posh Bukhari and his descendants profoundly influenced Sufism in the Indian subcontinent. The title 'Jahangasht' (World Wanderer) is often associated with the Suhrawardi masters of this lineage who traveled extensively. In the context of Kashmiri Sufism, the Bukhari Sayyids migrated and integrated into the local spiritual fabric, establishing khanqahs and spreading the Suhrawardi and Jalali traditions. They brought rich Central Asian scholastic and mystical traditions that hybridized with local Kashmiri practices.",
    "theologicalNotes": "The Bukhari lineage emphasized rigorous scholasticism combined with intense spiritual exercises, strongly defending the orthodoxy of Sufi practices against detractors.",
    "regionLinks": ["in_jk", "pk", "uz"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["suhrawardi", "jahangasht"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 88,
    "evidenceRecords": 0
  },
  {
    "id": "person_shukuruddin",
    "type": "saint",
    "slug": "baba-shukuruddin",
    "name": "Baba Shukuruddin",
    "alternateNames": ["Shukuruddin Wali"],
    "shortDescription": "Revered saint whose shrine overlooks the Wular Lake.",
    "longDescription": "Baba Shukuruddin was a prominent disciple of Nund Rishi. According to Kashmiri tradition, he was instructed by his master to meditate on a high peak overlooking the magnificent Wular Lake in northern Kashmir. He spent his life in deep contemplation and service to the local populace. His shrine, situated on a hillock called 'Shari Koh', is one of the most picturesque and spiritually potent locations in Kashmir, serving as a beacon of the Rishi order's love for meditating in the grandeur of nature.",
    "theologicalNotes": "His life exemplifies the Rishi practice of retreating to high mountains or deep forests to witness the majesty of God's creation, reflecting the Quranic injunction to ponder the signs in nature.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["rishi", "muraqaba", "nature"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 88,
    "evidenceRecords": 0
  },
  {
    "id": "person_hyder_reshi",
    "type": "saint",
    "slug": "baba-hyder-reshi",
    "name": "Baba Hyder Reshi",
    "alternateNames": ["Hardy Rishi", "Resh Mir Sahib"],
    "shortDescription": "Last of the major Rishi saints of Kashmir, known for his extreme asceticism.",
    "longDescription": "Baba Hyder Reshi (1504–1588 CE), often considered the last giant of the classical Rishi order, was a saint from Anantnag. He was heavily influenced by the Suhrawardi saint Sheikh Hamza Makhdoom, marking an interesting synthesis where an indigenous Rishi was guided by a formal Suhrawardi master. He never married, abstained entirely from eating meat, and spent his life farming and giving all his produce to the poor. His shrine in Anantnag remains a major center of pilgrimage.",
    "theologicalNotes": "He represents the formal bridging of the indigenous Kashmiri Rishi movement with the orthodox, globally structured Suhrawardi order.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks", "fa"],
    "relatedConcepts": ["rishi", "suhrawardi", "zuhd"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 90,
    "evidenceRecords": 0
  },
  {
    "id": "person_hussain_simnani",
    "type": "saint",
    "slug": "syed-hussain-simnani",
    "name": "Syed Hussain Simnani",
    "alternateNames": ["Hussain Simnani"],
    "shortDescription": "Early Persian Sufi who laid the groundwork for Shah-e-Hamadan's arrival in Kashmir.",
    "longDescription": "Syed Hussain Simnani was a cousin and advance emissary of Mir Sayyid Ali Hamadani. He arrived in Kashmir before Shah-e-Hamadan to assess the region and prepare the ground for the massive influx of Kubrawi Sufis. Settling in Kulgam, he was instrumental in establishing early khanqahs and peacefully introducing the local population to Islamic tenets. He also famously encountered Nund Rishi when Nund was a child, predicting his future greatness.",
    "theologicalNotes": "His early dawah efforts set the standard for peaceful, intellectually rigorous Islamic propagation in South Kashmir.",
    "regionLinks": ["in_jk", "ir"],
    "languageLinks": ["fa"],
    "relatedConcepts": ["kubrawiya", "dawah"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 89,
    "evidenceRecords": 0
  },
  {
    "id": "person_mir_muhammad",
    "type": "scholar",
    "slug": "mir-muhammad-hamadani",
    "name": "Mir Muhammad Hamadani",
    "alternateNames": ["Mir Muhammad"],
    "shortDescription": "Son of Shah-e-Hamadan who consolidated the Kubrawi order in Kashmir.",
    "longDescription": "Mir Muhammad Hamadani (1372–1450 CE) was the son of Mir Sayyid Ali Hamadani. Arriving in Kashmir at a young age after his father's passing, he took up the monumental task of consolidating the Kubrawi order's presence. He had a profound impact on the reigning monarch, Sultan Sikandar, guiding state policies towards Islamic orthodoxy. He authored treatises and established major educational institutions. His most historic spiritual action was meeting with and validating the indigenous saint Nund Rishi, formally connecting the Persian Kubrawi lineage with the Kashmiri Rishi movement.",
    "theologicalNotes": "His dialogue with Nund Rishi represents the ultimate theological handshake between imported orthodox Sufism and indigenous ascetic mysticism.",
    "regionLinks": ["in_jk", "ir"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["kubrawiya", "rishi", "sharia"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 0
  },
  {
    "id": "person_lutufuddin",
    "type": "saint",
    "slug": "baba-lutufuddin",
    "name": "Baba Lutufuddin",
    "alternateNames": ["Lutufuddin Rishi"],
    "shortDescription": "Prominent disciple of Nund Rishi known for his mystical absorption.",
    "longDescription": "Baba Lutufuddin was one of the early and most devoted disciples of Nund Rishi. Like many Rishis, he abandoned his worldly attachments and lived a life of rigorous seclusion and meditation. The Rishis under Nund Rishi were often assigned specific regions to meditate in and to serve the local populations; Lutufuddin was assigned a deeply forested area where he became known for his miraculous abilities and profound states of spiritual absorption (Jazb).",
    "theologicalNotes": "He exemplified the state of 'Majzub' (the divinely absorbed) within the Rishi tradition, living entirely oblivious to worldly concerns.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["rishi", "jazb"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 87,
    "evidenceRecords": 0
  },
  {
    "id": "person_yaqub_sarfi",
    "type": "scholar",
    "slug": "sheikh-yaqub-sarfi",
    "name": "Sheikh Yaqub Sarfi",
    "alternateNames": ["Ishan Sahib"],
    "shortDescription": "Brilliant polymath, poet, and Kubrawi master of 16th-century Kashmir.",
    "longDescription": "Sheikh Yaqub Sarfi (1521–1595 CE) was a towering intellectual and spiritual figure in Kashmir. A master of the Kubrawi order, he was also a prolific writer, poet, historian, and Islamic jurist. He traveled to Mecca, Medina, and Samarqand, acquiring authorizations (ijazas) from the greatest scholars of the Islamic world. His immense knowledge earned him the respect of the Mughal Emperor Akbar. Sarfi played a controversial but historically massive role by inviting Akbar to annex Kashmir to end the severe sectarian violence and misrule of the later Chak dynasty. He authored extensive tafsirs and poetry.",
    "theologicalNotes": "He represented the zenith of scholastic Sufism in Kashmir, perfectly balancing esoteric practices with high-level jurisprudence and political strategy.",
    "regionLinks": ["in_jk", "pk", "uz"],
    "languageLinks": ["fa", "ar", "ks"],
    "relatedConcepts": ["kubrawiya", "tafseer", "fiqh"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Yaqub_Sarfi"],
    "wikidataId": "Q8049184",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 1
  },
  {
    "id": "person_habibullah_nowsheri",
    "type": "poet",
    "slug": "habibullah-nowsheri",
    "name": "Habibullah Nowsheri",
    "alternateNames": ["Hubbi"],
    "shortDescription": "Ecstatic Sufi poet of Kashmir whose Persian verses are still sung in local gatherings.",
    "longDescription": "Khwaja Habibullah Nowsheri (1555–1617 CE), writing under the pen name 'Hubbi', was a highly celebrated Sufi poet and saint in Srinagar. He was deeply influenced by the Suhrawardi and Kubrawi masters of his time. Known for his ecstatic states, his poetry expresses an intense, overwhelming love for the Divine. His Persian poetry (Diwan-e-Hubbi) was incredibly popular among the masses and the elite alike. To this day, his mystical verses are a staple in traditional Kashmiri Sufi music (Sufiana Mausiqi) gatherings.",
    "theologicalNotes": "His work translates the complex metaphysics of Divine Love into highly emotional, musical Persian verse, making esoteric concepts accessible to the heart.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["fa", "ks"],
    "relatedConcepts": ["ishq", "sufiana_mausiqi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 90,
    "evidenceRecords": 0
  },
  {
    "id": "person_ahmad_tarqali",
    "type": "scholar",
    "slug": "ahmad-sahib-tarqali",
    "name": "Ahmad Sahib Tarqali",
    "alternateNames": ["Ahmad Tarqali"],
    "shortDescription": "Revered Sufi master and scholar associated with the spiritual heritage of Srinagar.",
    "longDescription": "Ahmad Sahib Tarqali was a notable Sufi mystic and scholar who contributed significantly to the spiritual atmosphere of Kashmir. Like many traditional Kashmiri saints, he operated a khanqah where he taught religious sciences alongside esoteric practices, offering spiritual solace and practical guidance to the people of the valley.",
    "theologicalNotes": "He emphasized the classic Sufi balance between outward legal observance (Sharia) and inward spiritual cultivation (Tariqa).",
    "regionLinks": ["in_jk"],
    "languageLinks": ["fa", "ks"],
    "relatedConcepts": ["tariqa", "sharia"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 85,
    "evidenceRecords": 0
  },
  {
    "id": "person_qasim_sahib",
    "type": "saint",
    "slug": "baba-qasim-sahib",
    "name": "Baba Qasim Sahib",
    "alternateNames": ["Qasim Sahib"],
    "shortDescription": "Mystic of the valley noted for his hidden spirituality and miracles.",
    "longDescription": "Baba Qasim Sahib is a revered figure in Kashmiri Sufi lore. He represents the tradition of the 'Malamati' (those who draw blame upon themselves) or hidden saints, who conceal their high spiritual rank behind ordinary or even seemingly erratic behavior to avoid public veneration. His shrine remains a site of quiet devotion for locals seeking spiritual and physical healing.",
    "theologicalNotes": "His path reflects the Malamatiyya tradition, prioritizing absolute sincerity (Ikhlas) with God by deliberately destroying one's public reputation.",
    "regionLinks": ["in_jk"],
    "languageLinks": ["ks"],
    "relatedConcepts": ["malamati", "ikhlas"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": [],
    "wikidataId": "",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 86,
    "evidenceRecords": 0
  },
  {
    "id": "person_mulla_shah",
    "type": "saint",
    "slug": "akhund-mulla-shah-badakhshi",
    "name": "Akhund Mulla Shah Badakhshi",
    "alternateNames": ["Mian Mir's Khalifa", "Mulla Shah"],
    "shortDescription": "Spiritual guide of Mughal Prince Dara Shikoh and a master of the Qadiri order.",
    "longDescription": "Akhund Mulla Shah Badakhshi (d. 1661 CE) was a profound Sufi master of the Qadiri order. Originally from Badakhshan, he settled in Kashmir and Lahore. He was the chief disciple of the legendary Mian Mir. Mulla Shah is most historically significant as the spiritual guide (Pir) of the Mughal Prince Dara Shikoh and his sister Princess Jahanara. Under Mulla Shah's guidance, Dara Shikoh undertook his massive project of finding the convergence between Islamic Sufism and Hindu Vedanta (Majma-ul-Bahrain). Mulla Shah oversaw the construction of a beautiful mosque and khanqah on the slopes of Hari Parbat in Srinagar.",
    "theologicalNotes": "He taught a highly sophisticated form of Wahdat al-Wujud that actively sought out the underlying unity in diverse religious traditions.",
    "regionLinks": ["in_jk", "pk", "af"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["qadiri", "wahdat_al_wujud", "majma_ul_bahrain"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Mullah_Shah_Badakhshi"],
    "wikidataId": "Q6934079",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 1
  }
];

const newRelationships = [
  {
    "id": "rel_lal_ded_nund_rishi",
    "type": "spiritual_mentor",
    "source": "person_lal_ded",
    "target": "person_nund_rishi",
    "properties": { "context": "Lal Ded profoundly influenced Nund Rishi; she is said to have nursed him as an infant and transmitted spiritual insight to him.", "strength": 100, "verified": true }
  },
  {
    "id": "rel_shah_hamadan_mir_muhammad",
    "type": "spiritual_lineage",
    "source": "person_mir_sayyid_ali_hamadani",
    "target": "person_mir_muhammad",
    "properties": { "context": "Mir Muhammad consolidated and expanded the Kubrawi mission started by his father, Shah-e-Hamadan.", "strength": 100, "verified": true }
  },
  {
    "id": "rel_makhdoom_khaki",
    "type": "spiritual_mentor",
    "source": "person_hamza_makhdoom",
    "target": "person_baba_dawood_khaki",
    "properties": { "context": "Baba Dawood Khaki was the chief Khalifa and intellectual systematizer for Makhdoom Sahib.", "strength": 95, "verified": true }
  },
  {
    "id": "rel_nund_rishi_zain_ud_din",
    "type": "spiritual_mentor",
    "source": "person_nund_rishi",
    "target": "person_zain_ud_din_wali",
    "properties": { "context": "Nund Rishi converted and guided the prince Zain-ud-Din, who became a foundational pillar of the Rishi order.", "strength": 95, "verified": true }
  },
  {
    "id": "rel_nund_rishi_payamuddin",
    "type": "spiritual_mentor",
    "source": "person_nund_rishi",
    "target": "person_payamuddin_reshi",
    "properties": { "context": "Baba Payamuddin renounced his worldly position to become a major disciple of Nund Rishi.", "strength": 90, "verified": true }
  }
];

// Append missing persons to core if they aren't there
newPersons.forEach(p => {
  if (!core.find(c => c.slug === p.slug)) {
    core.push({
      "class": "persons",
      "slug": p.slug,
      "name": p.name,
      "aliases": p.alternateNames,
      "canonicalImpact": p.shortDescription,
      "readinessScore": p.knowledgeDensityScore,
      "resilienceScore": 90,
      "confidenceLayer": "High",
      "verificationStatus": "Verified",
      "evidenceRecords": p.evidenceRecords,
      "disputeStatus": "None",
      "relatedQuestions": []
    });
  }
});

// Add to registry
newPersons.forEach(p => {
  if (!registry.find(r => r.slug === p.slug || r.id === p.id)) {
    registry.push(p);
  }
});

// Add to rels
newRelationships.forEach(r => {
  if (!rels.find(rel => rel.id === r.id)) {
    rels.push(r);
  }
});

fs.writeFileSync(corePath, JSON.stringify(core, null, 2));
fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));
fs.writeFileSync(relsPath, JSON.stringify(rels, null, 2));

console.log(`Enriched registry with ${newPersons.length} Kashmiri figures and ${newRelationships.length} relationships.`);
