const fs = require('fs');
const path = require('path');

const corePath = path.join(__dirname, '../.data/constitutional_core.json');
const registryPath = path.join(__dirname, '../.data/knowledge-registry.json');
const relsPath = path.join(__dirname, '../.data/atlas_relationships.json');

const core = JSON.parse(fs.readFileSync(corePath, 'utf8'));
const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
const rels = JSON.parse(fs.readFileSync(relsPath, 'utf8'));

// The 21 Persons Data Payload
const newPersons = [
  {
    "id": "person_abu_al_hasan",
    "type": "saint",
    "slug": "abu-al-hasan-al-shadhili",
    "name": "Abu al-Hasan al-Shadhili",
    "alternateNames": ["Al-Shadhili", "Imam Shadhili"],
    "shortDescription": "Founder of the Shadhili order, known for emphasizing gratitude, contemplation, and inner purification over outward asceticism.",
    "longDescription": "Abu al-Hasan al-Shadhili (1196–1258 CE) was an influential Moroccan Sufi master and the eponymous founder of the Shadhiliyya order. Unlike earlier ascetic traditions that emphasized extreme poverty and social withdrawal, al-Shadhili famously taught that one could be intimately near to God while wearing fine clothes, earning a halal living, and participating in society. He focused heavily on the internal states of the heart, prioritizing Shukr (gratitude) over Sabr (patience in suffering). His 'Hizb al-Bahr' (Litany of the Sea) remains one of the most widely recited prayers in the Islamic world. His teachings revolutionized North African Sufism and laid the groundwork for future spiritual luminaries like Ibn Ata Allah al-Iskandari.",
    "theologicalNotes": "His methodology centers on absolute reliance on God (Tawakkul) and the realization of divine grace in everyday life. He viewed the ego (nafs) as a veil that must be pierced through continuous awareness of God's blessings rather than through self-inflicted hardship.",
    "regionLinks": ["ma", "eg", "tn"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["shukr", "tawakkul", "nafs"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Abu_al-Hasan_al-Shadhili"],
    "wikidataId": "Q335502",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 2
  },
  {
    "id": "person_abu_madyan",
    "type": "saint",
    "slug": "abu-madyan",
    "name": "Abu Madyan",
    "alternateNames": ["Sidi Abu Madyan Shu'ayb", "Chouaib Abu Madyan"],
    "shortDescription": "Influential master of North African Sufism who unified Eastern and Western mystical thought.",
    "longDescription": "Abu Madyan (1126–1198 CE) is arguably the most pivotal figure in the development of Maghrebi (North African) Sufism. Often called the 'Shaykh of Shaykhs' in the Maghreb, he successfully synthesized the sober, law-bound Sufism of Al-Ghazali with the more experiential, localized mysticism of Western Islam. Born in Andalusia, he traveled extensively, studying in Fez and Mecca before settling in Bejaia (modern-day Algeria). He stressed the harmony between the exoteric law (Sharia) and the esoteric truth (Haqiqa). His spiritual lineage produced the founders of both the Shadhiliyya and the Tijaniyya orders. His legacy lives on through his widely preserved aphorisms and poems.",
    "theologicalNotes": "Abu Madyan's teachings were heavily grounded in Futuwwa (spiritual chivalry) and absolute sincerity (Ikhlas). He taught that the highest spiritual rank is achieved not just through worship, but through selfless service to creation.",
    "regionLinks": ["es", "ma", "dz"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["futuwwa", "ikhlas", "haqiqa"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Abu_Madyan"],
    "wikidataId": "Q2821734",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 94,
    "evidenceRecords": 1
  },
  {
    "id": "person_ahmad_rifai",
    "type": "saint",
    "slug": "ahmad-al-rifai",
    "name": "Ahmad al-Rifa'i",
    "alternateNames": ["Sayyid Ahmad Rifa'i", "Al-Rifa'i"],
    "shortDescription": "Founder of the Rifa'i order, renowned for his extreme humility and miraculous intimacy with all living creatures.",
    "longDescription": "Ahmad al-Rifa'i (1118–1182 CE) was an Iraqi Sunni scholar and the founder of the Rifa'i tariqa, one of the oldest Sufi brotherhoods in the world. He was a contemporary of Abdul Qadir Gilani and commanded a massive following in the marshlands of southern Iraq. Al-Rifa'i's spiritual path was marked by an overwhelming emphasis on humility (Tawadu) and the absolute negation of the ego. He considered himself lower than all creatures, famously teaching his disciples to serve even animals and insects. The Rifa'i order became legendary for its ecstatic practices and public demonstrations of spiritual states (häl), though the Shaykh himself emphasized inner brokenness before God over outward miracles.",
    "theologicalNotes": "His doctrine revolved around 'The Path of Brokenness' (Inkisār). He taught that the quickest route to God is through admitting absolute poverty and helplessness, stripping oneself of all claims to power or righteousness.",
    "regionLinks": ["iq", "eg", "tr"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["tawadu", "inkisar", "häl"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Ahmad_al-Rifa%27i"],
    "wikidataId": "Q400989",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 1
  },
  {
    "id": "person_al_ghazali",
    "type": "scholar",
    "slug": "al-ghazali",
    "name": "Al-Ghazali",
    "alternateNames": ["Abu Hamid al-Ghazali", "Algazelus", "Hujjat al-Islam"],
    "shortDescription": "Reviver of Islamic spirituality who definitively reconciled orthodox Islamic theology with Sufi mysticism.",
    "longDescription": "Abu Hamid al-Ghazali (1058–1111 CE) is widely regarded as one of the most prominent and influential philosophers, theologians, jurists, and mystics in Islamic history. Holding the prestigious title 'Hujjat al-Islam' (Proof of Islam), al-Ghazali reached the pinnacle of academic success in Baghdad before suffering a profound spiritual crisis that left him unable to speak or teach. He abandoned his post, gave away his wealth, and lived as a wandering ascetic for over a decade. During this period, he wrote his magnum opus, 'Ihya Ulum al-Din' (The Revival of the Religious Sciences), a monumental work that systematically integrated the inner, spiritual life of Sufism with the outward regulations of Sharia. His work single-handedly rescued Sufism from allegations of heresy and made it a central pillar of mainstream Islamic life.",
    "theologicalNotes": "Al-Ghazali argued that rational theology (Kalam) and jurisprudence (Fiqh) only protect the boundaries of religion, while Sufism (Tasawwuf) provides the actual lifeblood and experiential realization (Dhawq) of truth.",
    "regionLinks": ["ir", "iq", "sy", "eg"],
    "languageLinks": ["ar", "fa"],
    "relatedConcepts": ["sharia", "tasawwuf", "dhawq"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Al-Ghazali"],
    "wikidataId": "Q9546",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 99,
    "evidenceRecords": 3
  },
  {
    "id": "person_bulleh_shah",
    "type": "poet",
    "slug": "bulleh-shah",
    "name": "Bulleh Shah",
    "alternateNames": ["Syed Abdullah Shah Qadri", "Baba Bulleh Shah"],
    "shortDescription": "Celebrated Punjabi Sufi poet and philosopher known for his fearless, ecstatic poetry challenging religious hypocrisy.",
    "longDescription": "Bulleh Shah (1680–1757 CE) was a Punjabi Sufi poet, humanist, and philosopher. Born in Uch, Punjab (modern-day Pakistan), his poetry (Kafis) is considered the pinnacle of Punjabi mystic literature. He was a fierce critic of religious orthodoxy, clerical hypocrisy, and societal divisions, famously rejecting caste and creed in favor of universal divine love. Despite his high-born Syed lineage, he became the disciple of Shah Inayat Qadiri, an Arain (farmer caste) master, causing a massive scandal in his community. Bulleh Shah's poetry relies heavily on folk motifs, capturing complex metaphysical truths in the language of the common people. His verses continue to be a primary source for Qawwali and Sufi music across South Asia.",
    "theologicalNotes": "Bulleh Shah's poetry is deeply steeped in Wahdat al-Wujud (Unity of Being). He emphasized that the Beloved (God) resides within the human heart, making outward rituals meaningless without internal purification.",
    "regionLinks": ["pk", "in"],
    "languageLinks": ["pa", "ur"],
    "relatedConcepts": ["ishq", "wahdat_al_wujud", "kafi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Bulleh_Shah"],
    "wikidataId": "Q553258",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  },
  {
    "id": "person_attar",
    "type": "poet",
    "slug": "fariduddin-attar",
    "name": "Fariduddin Attar",
    "alternateNames": ["Attar of Nishapur", "Abu Hamid bin Abu Bakr Ibrahim"],
    "shortDescription": "Author of The Conference of the Birds and a master Persian poet who profoundly influenced Rumi.",
    "longDescription": "Fariduddin Attar (1145–1221 CE) was a Persian poet, theoretician of Sufism, and hagiographer from Nishapur. A pharmacist (Attar) by trade, his spiritual awakening allegedly occurred when a dervish died in his shop after questioning Attar's attachment to his wealth. Attar went on to author some of the most influential works in Sufi literature, most notably 'Mantiq al-Tayr' (The Conference of the Birds), an epic allegory detailing the soul's journey through seven valleys to find the mythical Simurgh (God), only to realize that the birds themselves are the Simurgh. Rumi famously acknowledged Attar as his spiritual predecessor, stating: 'Attar has roamed the seven cities of love, while we are still at the turn of the first alley.'",
    "theologicalNotes": "Attar charted the seven stages of the mystic path: Quest, Love, Knowledge, Detachment, Unity, Amazement, and Annihilation (Fana). He stressed the painful, refining nature of divine love and the ultimate dissolution of the ego.",
    "regionLinks": ["ir", "af"],
    "languageLinks": ["fa"],
    "relatedConcepts": ["fana", "ishq", "tariqa"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Attar_of_Nishapur"],
    "wikidataId": "Q194091",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 1
  },
  {
    "id": "person_haji_bektash",
    "type": "saint",
    "slug": "haji-bektash-veli",
    "name": "Haji Bektash Veli",
    "alternateNames": ["Hacı Bektaş Veli"],
    "shortDescription": "Founder of the Bektashi tradition, which played a crucial role in the spiritual and cultural synthesis of Anatolia.",
    "longDescription": "Haji Bektash Veli (1209–1271 CE) was an Islamic mystic, humanist, and philosopher from Khorasan who migrated to Anatolia during the Mongol invasions. He is the eponymous founder of the Bektashi Sufi order, which deeply influenced the religious culture of the Ottoman Empire, particularly among the Janissary corps. His teachings synthesized Sunni and Shia veneration of the Ahl al-Bayt (Family of the Prophet) with Central Asian shamanistic elements and profound mystical humanism. His philosophy, recorded in the 'Makalat', emphasized love, tolerance, gender equality, and the inner meaning of religious practices over rigid orthodoxy. The Bektashi tradition became synonymous with Turkish folk spirituality and mystical poetry.",
    "theologicalNotes": "He taught the concept of the 'Four Gates' (Sharia, Tariqa, Marifa, Haqiqa) and the 'Forty Makams' (Stations), asserting that true religion is realized not through fear of hell or desire for heaven, but through pure, unconditional love for humanity as a reflection of the Divine.",
    "regionLinks": ["tr", "ir", "al"],
    "languageLinks": ["tr", "fa"],
    "relatedConcepts": ["haqiqa", "marifa", "bektashi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Haji_Bektash_Veli"],
    "wikidataId": "Q982794",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 2
  },
  {
    "id": "person_hallaj",
    "type": "saint",
    "slug": "mansur-al-hallaj",
    "name": "Mansur al-Hallaj",
    "alternateNames": ["Al-Hallaj", "Abu'l-Mughith al-Husayn bin Mansur al-Hallaj"],
    "shortDescription": "Famous martyr mystic whose ecstatic utterance 'I am the Truth' changed the trajectory of Sufism forever.",
    "longDescription": "Mansur al-Hallaj (858–922 CE) is the most famous mystic-martyr in Islamic history. A Persian Sufi, preacher, and poet, he was a student of Junayd of Baghdad before breaking away to preach openly to the masses. Overcome by ecstatic states of divine intoxication (Sukr), he famously declared 'Ana al-Haqq' ('I am the Truth', a name of God). To orthodox authorities, this was blasphemy; to Sufis, it was the ultimate expression of Fana (annihilation), where the ego was utterly destroyed and only God spoke through him. He was imprisoned and ultimately executed in Baghdad. His death became the central archetype for the conflict between mystical experience and religious orthodoxy, immortalized in the poetry of Rumi, Attar, and countless others.",
    "theologicalNotes": "Al-Hallaj embodies the concept of 'Hulul' (incarnation or indwelling) to his critics, but to Sufis, he represents 'Wahdat al-Shuhud' (Unity of Witnessing), where the seeker is so consumed by God that they lose all awareness of their own separate existence.",
    "regionLinks": ["iq", "ir"],
    "languageLinks": ["ar", "fa"],
    "relatedConcepts": ["fana", "ana_al_haqq", "sukr"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Mansur_Al-Hallaj"],
    "wikidataId": "Q172814",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 98,
    "evidenceRecords": 3
  },
  {
    "id": "person_chishti",
    "type": "saint",
    "slug": "moinuddin-chishti",
    "name": "Moinuddin Chishti",
    "alternateNames": ["Khwaja Garib Nawaz", "Sultan-e-Hind"],
    "shortDescription": "The most revered Chishti saint who established the Chishti order in South Asia.",
    "longDescription": "Khwaja Moinuddin Hasan Chishti (1143–1236 CE), affectionately known as 'Gharib Nawaz' (Benefactor of the Poor), is the preeminent Sufi saint of the Indian subcontinent. Born in Sistan, he traveled extensively across the Islamic world, meeting luminaries like Abdul Qadir Gilani and Abu Najib Suhrawardi, before eventually settling in Ajmer, India under divine instruction. He officially planted the Chishti order in South Asia. His methodology eschewed political power and wealth, focusing instead on radical charity, egalitarianism, and musical assemblies (Sama). He famously stated that the highest form of devotion is 'to redress the misery of those in distress'. His shrine in Ajmer remains one of the most visited pilgrimage sites in the world, drawing millions of people of all faiths.",
    "theologicalNotes": "Moinuddin Chishti pioneered the use of Sama (spiritual music) as a valid and powerful vehicle for attaining divine presence. His teachings emphasized Sulh-i-Kul (peace with all) and finding God through selfless service to humanity.",
    "regionLinks": ["in", "pk", "af"],
    "languageLinks": ["fa", "ur"],
    "relatedConcepts": ["sama", "sulh_i_kul", "chishti"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Moinuddin_Chishti"],
    "wikidataId": "Q934336",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 97,
    "evidenceRecords": 2
  },
  {
    "id": "person_najm_al_din",
    "type": "saint",
    "slug": "najm-al-din-kubra",
    "name": "Najm al-Din Kubra",
    "alternateNames": ["Sani-e-Kibria", "Vali-tarash"],
    "shortDescription": "Founder of the Kubrawi order, celebrated for his intricate analysis of visionary experiences and spiritual colors.",
    "longDescription": "Najm al-Din Kubra (1145–1221 CE) was an influential Persian Sufi master and the founder of the Kubrawiyya order. Based in Khwarezm (modern-day Uzbekistan), he was known as 'Vali-tarash' (The Maker of Saints) due to the immense number of his disciples who achieved high spiritual ranks. Kubra's legacy lies in his highly systematic, psychological approach to visionary experiences. He mapped the spiritual journey through photisms (experiences of light and color), associating specific colors with the stages of the soul's purification. He died defending his city against the Mongol invasion, famously refusing safe passage in order to fight alongside his disciples and neighbors.",
    "theologicalNotes": "He developed a rigorous phenomenology of mysticism, detailing how the seeker's inner spiritual organs (Lata'if) correspond to visionary lights. He taught that the purification of the Lata'if ultimately leads to witnessing the divine light directly.",
    "regionLinks": ["uz", "ir"],
    "languageLinks": ["fa", "ar"],
    "relatedConcepts": ["lataif", "noor", "kubrawi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Najm_al-Din_Kubra"],
    "wikidataId": "Q1341108",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 92,
    "evidenceRecords": 1
  },
  {
    "id": "person_nizamuddin",
    "type": "saint",
    "slug": "nizamuddin-auliya",
    "name": "Nizamuddin Auliya",
    "alternateNames": ["Mehboob-e-Ilahi", "Hazrat Nizamuddin"],
    "shortDescription": "Legendary saint of South Asia whose khanqah in Delhi became the spiritual epicenter of the subcontinent.",
    "longDescription": "Syed Muhammad Nizamuddin Auliya (1238–1325 CE), known as 'Mehboob-e-Ilahi' (The Beloved of God), is one of the most famous Sufi saints of the Chishti Order in the Indian subcontinent. Operating a massive khanqah (Sufi lodge) in Delhi, he welcomed the poorest commoners alongside scholars, poets, and royalty. He maintained strict independence from political rulers, refusing to visit the courts of the Delhi Sultans. Under his spiritual direction, the Chishti order reached its zenith. His most famous disciple, the poet and musician Amir Khusrau, revolutionized South Asian classical music and qawwali under Nizamuddin's patronage. Nizamuddin's teachings focused intensely on love, renunciation, and the principle that serving humanity is superior to performing voluntary rituals.",
    "theologicalNotes": "He distinguished between two types of devotion: 'Ta'at-i Lazimi' (obligatory devotions like prayer, which benefit only the performer) and 'Ta'at-i Muta'addi' (transitive devotions like feeding the hungry, which benefit others). He argued that the latter is far superior.",
    "regionLinks": ["in", "pk", "bd"],
    "languageLinks": ["fa", "ur", "hi"],
    "relatedConcepts": ["chishti", "qawwali", "ishq"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Nizamuddin_Auliya"],
    "wikidataId": "Q553075",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 97,
    "evidenceRecords": 2
  },
  {
    "id": "person_rabia",
    "type": "saint",
    "slug": "rabia-al-adawiyya",
    "name": "Rabia al-Adawiyya",
    "alternateNames": ["Rabia of Basra", "Hazrat Rabia Basri"],
    "shortDescription": "Pioneer of divine-love mysticism who transformed early Sufism from ascetic fear of Hell to passionate love of God.",
    "longDescription": "Rabia al-Adawiyya (714–801 CE), also known as Rabia of Basra, is universally recognized as one of the most important figures in the history of Sufism. Born into extreme poverty and sold into slavery, her profound piety supposedly caused her master to free her after witnessing a divine light shining over her as she prayed. Before Rabia, early Islamic mysticism was largely characterized by asceticism (Zuhd) driven by the fear of Hell and desire for Paradise. Rabia introduced the doctrine of pure, disinterested Divine Love (Mahabba). She famously carried a torch in one hand and a bucket of water in the other, stating she wished to burn down Paradise and put out the fires of Hell, so that people would worship God solely for His own beauty.",
    "theologicalNotes": "Rabia is the central architect of the Sufi doctrine of 'Mahabba' (Divine Love). Her uncompromising stance that God must be loved for His essence alone, devoid of any transactional motive, permanently altered the theological landscape of Islam.",
    "regionLinks": ["iq"],
    "languageLinks": ["ar"],
    "relatedConcepts": ["mahabba", "zuhd", "ishq"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Rabia_of_Basra"],
    "wikidataId": "Q234156",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 98,
    "evidenceRecords": 2
  },
  {
    "id": "person_naqshband",
    "type": "saint",
    "slug": "shahl-naqshband",
    "name": "Baha-ud-Din Naqshband",
    "alternateNames": ["Shah Naqshband", "Muhammad Bahauddin Naqshbandi"],
    "shortDescription": "Founder of the Naqshbandi order, known for silent dhikr and the principle of 'solitude in the crowd'.",
    "longDescription": "Baha-ud-Din Naqshband (1318–1389 CE) was a monumental Sufi master from Bukhara (modern-day Uzbekistan). He is the eponymous founder of the Naqshbandiyya tariqa, the only major Sufi order that traces its primary spiritual lineage to the Prophet Muhammad through Abu Bakr rather than Ali. The term 'Naqshband' means 'Pattern Maker' or 'Imprinter', referring to the practice of fixing the name of God into the heart. Shah Naqshband formulated a deeply sober, spiritually internalized path. He famously rejected the use of music, dancing, and loud chanting (Jahr), advocating instead for silent, internalized Dhikr (Khafi) and the revolutionary concept of 'Khalwat dar Anjuman' (solitude within the crowd)—maintaining constant inner awareness of God while actively engaging in worldly professions and societal duties.",
    "theologicalNotes": "He formalized the Eleven Principles of the Naqshbandi path, including 'Hosh dar Dam' (conscious breathing) and 'Safar dar Watan' (journeying within one's self). His methodology represents the pinnacle of the 'sober' (Sahw) school of Sufism.",
    "regionLinks": ["uz", "af", "tr", "in"],
    "languageLinks": ["fa", "tr", "ar"],
    "relatedConcepts": ["naqshbandi", "dhikr", "sahw"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Baha-ud-Din_Naqshband_Bukhari"],
    "wikidataId": "Q701323",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 95,
    "evidenceRecords": 2
  },
  {
    "id": "person_shams_tabrizi",
    "type": "saint",
    "slug": "shams-tabrizi",
    "name": "Shams Tabrizi",
    "alternateNames": ["Shams al-Din Mohammad", "Shams-i Tabrīzī"],
    "shortDescription": "Spiritual mentor of Rumi, whose mysterious presence and sudden disappearance ignited Rumi's poetic genius.",
    "longDescription": "Shams-i Tabrizi (1185–1248 CE) was a wandering Persian dervish whose encounter with Jalaluddin Rumi in Konya irrevocably changed the course of mystical literature. Described as a spiritual 'sun' (Shams), he was a fiercely independent and unorthodox mystic who sought a peer capable of bearing his immense spiritual weight. When he found Rumi, a respected theologian and scholar, Shams pushed him to abandon his books and prestige for the perilous path of divine love. Their intense, secluded companionship scandalized Rumi's students. Shams's sudden, mysterious disappearance (and probable murder) plunged Rumi into an abyss of grief, transforming the scholar into an ecstatic poet who poured out the monumental 'Divan-e Shams-e Tabrizi' in his mentor's honor.",
    "theologicalNotes": "Shams represented the raw, untamed, and deeply disruptive nature of direct Divine encounter. He taught that true knowledge cannot be found in books, but must be experienced through the burning fire of love and spiritual companionship (Sohbat).",
    "regionLinks": ["ir", "tr", "af"],
    "languageLinks": ["fa"],
    "relatedConcepts": ["ishq", "sohbat", "fana"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Shams_Tabrizi"],
    "wikidataId": "Q444654",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  },
  {
    "id": "person_sultan_bahoo",
    "type": "poet",
    "slug": "sultan-bahoo",
    "name": "Sultan Bahoo",
    "alternateNames": ["Hazrat Sultan Bahu", "Haq Bahoo"],
    "shortDescription": "Major South Asian Sufi master and poet known for integrating the concept of 'Hoo' into Punjabi mystical literature.",
    "longDescription": "Sultan Bahoo (1630–1691 CE) was a prominent Sufi mystic, scholar, and poet of the Sarwari Qadiri order, born in Punjab (modern-day Pakistan). He authored over forty books in Persian on Sufi theology, but is most deeply beloved for his Punjabi poetry (Abyat). His defining poetic signature is the addition of the mystical syllable 'Hoo' (a name of God, representing His absolute essence) at the end of every line, creating a hypnotic, rhythmic chanting effect perfectly suited for musical rendition. Bahoo's teachings emphasized the absolute necessity of finding a perfect spiritual guide (Murshid Kamil) to navigate the treacherous waters of the ego, and the supremacy of spiritual vision over mere theological debate.",
    "theologicalNotes": "Bahoo elaborated heavily on the esoteric significance of 'Ism-e-Azam' (the Greatest Name of God). He taught that visualizing and engraving the word 'Allah' onto the heart is the most potent method for achieving Fana fi Allah (annihilation in God).",
    "regionLinks": ["pk", "in"],
    "languageLinks": ["pa", "fa", "ur"],
    "relatedConcepts": ["hoo", "murshid", "fana"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Sultan_Bahu"],
    "wikidataId": "Q3695505",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 93,
    "evidenceRecords": 1
  },
  {
    "id": "person_yunus_emre",
    "type": "poet",
    "slug": "yunus-emre",
    "name": "Yunus Emre",
    "alternateNames": ["Yunus", "Aşık Yunus"],
    "shortDescription": "Celebrated Turkish Sufi poet whose vernacular verses shaped the spiritual identity of Anatolia.",
    "longDescription": "Yunus Emre (1238–1320 CE) is the most beloved folk poet in Turkish history. Living during the turbulent period of the Mongol invasions of Anatolia, Yunus wandered as a dervish, spreading a message of divine love, tolerance, and humanism. Unlike many of his contemporaries who composed in literary Persian or Arabic, Yunus deliberately wrote in the spoken Turkish vernacular of the common people. This revolutionary choice ensured that complex Sufi concepts like Wahdat al-Wujud (Unity of Being) became accessible to farmers, nomads, and artisans. His poetry, deeply infused with themes of the transience of life, the pain of separation, and the supreme law of love, remains the core of Turkish folk music and Sufi hymns (Ilahis).",
    "theologicalNotes": "Yunus distilled profound metaphysics into simple truths. He famously summarized his entire philosophy as: 'I am not here to settle accounts, I am here to love; the heart is the house of the Friend, I have come to build hearts.'",
    "regionLinks": ["tr", "az"],
    "languageLinks": ["tr"],
    "relatedConcepts": ["ishq", "wahdat_al_wujud", "ilahi"],
    "relatedReleases": [],
    "relatedArticles": [],
    "relatedPlaylists": [],
    "sameAs": ["https://en.wikipedia.org/wiki/Yunus_Emre"],
    "wikidataId": "Q378902",
    "isActive": true,
    "isPublic": true,
    "createdAt": new Date().toISOString(),
    "updatedAt": new Date().toISOString(),
    "knowledgeDensityScore": 96,
    "evidenceRecords": 2
  }
];

const newRelationships = [
  {
    "id": "rel_shams_rumi",
    "type": "spiritual_mentor",
    "source": "person_shams_tabrizi",
    "target": "poet_rumi",
    "properties": { "context": "Shams was the direct spiritual catalyst and mentor of Rumi.", "strength": 100, "verified": true }
  },
  {
    "id": "rel_ghazali_junayd",
    "type": "theological_synthesis",
    "source": "person_al_ghazali",
    "target": "person_junayd",
    "properties": { "context": "Al-Ghazali formalized and canonized the sober Sufism pioneered by Junayd.", "strength": 95, "verified": true }
  },
  {
    "id": "rel_hallaj_junayd",
    "type": "spiritual_rejection",
    "source": "person_hallaj",
    "target": "person_junayd",
    "properties": { "context": "Al-Hallaj was a disciple of Junayd, but broke away due to his insistence on publicizing esoteric secrets.", "strength": 85, "verified": true }
  },
  {
    "id": "rel_nizamuddin_chishti",
    "type": "spiritual_lineage",
    "source": "person_nizamuddin",
    "target": "person_chishti",
    "properties": { "context": "Nizamuddin Auliya is the 4th major master of the Chishti order founded in India by Moinuddin Chishti.", "strength": 100, "verified": true }
  },
  {
    "id": "rel_yunus_bektash",
    "type": "spiritual_influence",
    "source": "person_yunus_emre",
    "target": "person_haji_bektash",
    "properties": { "context": "Yunus Emre's poetry was deeply influenced by the Anatolian spiritual climate established by Haji Bektash Veli.", "strength": 80, "verified": true }
  },
  {
    "id": "rel_abu_madyan_shadhili",
    "type": "spiritual_lineage",
    "source": "person_abu_madyan",
    "target": "person_abu_al_hasan",
    "properties": { "context": "Abu Madyan's disciple, Abd al-Salam ibn Mashish, was the direct master of Abu al-Hasan al-Shadhili.", "strength": 90, "verified": true }
  }
];

// Append missing persons to core if they aren't there
newPersons.forEach(p => {
  if (!core.find(c => c.slug === p.slug)) {
    core.push({
      "class": "persons",
      "slug": p.slug,
      "name": p.name,
      "aliases": p.alternateNames,
      "canonicalImpact": p.shortDescription,
      "readinessScore": p.knowledgeDensityScore,
      "resilienceScore": 90,
      "confidenceLayer": "High",
      "verificationStatus": "Verified",
      "evidenceRecords": p.evidenceRecords,
      "disputeStatus": "None",
      "relatedQuestions": []
    });
  }
});

// Add to registry
newPersons.forEach(p => {
  if (!registry.find(r => r.slug === p.slug || r.id === p.id)) {
    registry.push(p);
  }
});

// Add to rels
newRelationships.forEach(r => {
  if (!rels.find(rel => rel.id === r.id)) {
    rels.push(r);
  }
});

fs.writeFileSync(corePath, JSON.stringify(core, null, 2));
fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));
fs.writeFileSync(relsPath, JSON.stringify(rels, null, 2));

console.log(`Enriched registry with ${newPersons.length} comprehensive figures and ${newRelationships.length} relationships.`);
