import { CMSRelease } from '@/lib/cms-storage';

export type PersistedCMSRelease = Omit<CMSRelease, 'createdAt' | 'updatedAt'> & {
  createdAt?: string;
  updatedAt?: string;
};

export interface ReleaseProjection {
  id: string;
  slug: string;
  title: string;
  canonicalTitle: string | null;
  canonicalStatus: string | null;
  governanceOrigin: string | null;
  metadataStatus: string | null;
  canonicalThumbnail: string | null;
  thumbnailUrl: string | null;
  youtubeId: string | null;
  youtubeTitle: string | null;
  youtubeThumbnailUrl: string | null;
  youtubeUrl: string | null;
  youtubeChannelId: string | null;
  youtubeChannelUrl: string | null;
  youtubePlaylistId: string | null;
  status: string;
  visibility: string | null;
  format: string | null;
  releaseType: string | null;
  category: string | null;
  source: string | null;
  contentReadinessState: string | null;
  webOnly: boolean | null;
  description: string | null;
  writerName: string | null;
  writerNameUrdu: string | null;
  vocalistName: string | null;
  vocalistNameUrdu: string | null;
  producerName: string | null;
  tags: string[] | null;
  releaseDate: string | null;
  publishedAt: string | null;
  durationSeconds: number | null;
  durationFormatted: string | null;
  viewCount: number | null;
  likeCount: number | null;
  availableLanguages: string[] | null;
  defaultLanguage: string | null;
  enableLyrics: boolean | null;
  enableCommentary: boolean | null;
  enableSponsors: boolean | null;
  enableAdoption: boolean | null;
  enableCredits: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
  registryOrder: number | null;
}

export interface ReleaseRow {
  id: string;
  slug: string;
  title: string;
  canonical_title: string | null;
  canonical_status: string | null;
  governance_origin: string | null;
  metadata_status: string | null;
  canonical_thumbnail: string | null;
  thumbnail_url: string | null;
  youtube_id: string | null;
  youtube_title: string | null;
  youtube_thumbnail_url: string | null;
  youtube_url: string | null;
  youtube_channel_id: string | null;
  youtube_channel_url: string | null;
  youtube_playlist_id: string | null;
  status: string;
  visibility: string | null;
  format: string | null;
  release_type: string | null;
  category: string | null;
  source: string | null;
  content_readiness_state: string | null;
  web_only: boolean | null;
  description: string | null;
  writer_name: string | null;
  writer_name_urdu: string | null;
  vocalist_name: string | null;
  vocalist_name_urdu: string | null;
  producer_name: string | null;
  tags: string[] | null;
  release_date: Date | null;
  published_at: Date | null;
  duration_seconds: number | null;
  duration_formatted: string | null;
  view_count: number | null;
  like_count: number | null;
  available_languages: string[] | null;
  default_language: string | null;
  enable_lyrics: boolean | null;
  enable_commentary: boolean | null;
  enable_sponsors: boolean | null;
  enable_adoption: boolean | null;
  enable_credits: boolean | null;
  created_at: Date | null;
  updated_at: Date | null;
  db_created_at: Date;
  db_updated_at: Date;
  registry_order: number | null;
  payload: any;
}
